### ISSUE TITLE
Komentoj en eventoj

### ISSUE THREAD

**Issue by shayani** [eventaservo/eventaservo#10]
Kiel komenton ni povus aldoni al la eventoj?

Kelkfoje mi ŝatus komenti pri evento. Ekzemple, gratuli pri la evento aŭ demandi ion.

Mi planas ebligi ĉiuj evento havi koment-sesion. Nur registritaj uzantoj kapablos komenti kaj la eventa orgnizanto ricevos ricevos retpoŝtmesaĝon pri novaj komentoj.

**Comment by JabieroKubo** [comment]
tio estos tre utila.

**Comment by ortegacmanuel** [comment]
@shayani Mi pretas helpi pri realigo de tiu ĉi ideo. Mia plano estas krei plej bazan funkcion tiel ke ni facile povu evoluigi ĝin poste.

Jen kion mi planas fari:
- Aldoni novan `Comment` modelon kiu apartenu al `Events`
- Aldoni novan kontrolilon `CommentsController` kiu respondecu pri kreado kaj redaktado de komentoj.

Kion vi opinias? Mi atendos vian konfirmon kaj okaze de jesa konfirmo mi laboros pri tio ĉi en la venontaj do semajnoj..mi devas trovi iom da libera tempo por okupiĝi pri ĝi ;)

**Comment by shayani** [comment]
Dankegon @ortegacmanuel. Estas bona propono. Kreu 'forkon' kaj alŝutu la kodon. Mi helpos vin se necesas :)
