### ISSUE TITLE
Minuskloj: ĉu eblas "respekti" usklecon de nomoj de lokoj?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#100]
Herzberg am Harz iĝas 'Herzberg Am Harz'. Ĉu eblas minuskligi la 'am'? https://eventaservo.org/Eŭropo/Germanio/Herzberg%20am%20Harz

(evidente estas nur ekzemple okazo kaj validu por ĉiuj nomoj)

![127D0C04-E668-415F-8029-06AF753F5CB7](https://user-images.githubusercontent.com/45429699/57726832-48c8d400-7690-11e9-9384-ded1037cc902.jpeg)

**Comment by shayani** [comment]
Teknike jes, tamen ne estas bona ideo. Multaj homoj ofte tajpos la nomon tute minuskle aŭ majŭskle. Mi preferas aŭtomate "titoligi" ĝin (https://apidock.com/rails/String/titleize).
