### ISSUE TITLE
Admin: sendi mesaĝon ankaŭ kiam iu kreas konton

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#101]
Ĉu vi povus ankaŭ aŭtomate sendi al mi retmesaĝon kiam iu kreis konton en ES? Mi aktive invitas homojn krei konton por ke mi povu igi ilin 'Eventa administranto' kaj tiel mi povus ekscii ke ili faris.

**Comment by shayani** [comment]
f0df8fdee686d04243af9e3b852876fdf0074ca1
