### ISSUE TITLE
Eventoj kun "horzonaj problemoj" kiujn Yves ne kapablas ripari

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#103]
Estu Eŭropo/Bratislavo https://eventaservo.org/eventoj/ctbkvMu3gft5kVUp
Estu 00:00 - 00:00 https://eventaservo.org/eventoj/ZMQHEVXK4KuELUlK
Estu 00:00 - 00:00 https://eventaservo.org/eventoj/Hfy-n6YSzew0CrCd
Estu 00:00 - 00:00 https://eventaservo.org/eventoj/RD7oa8F4nSuXnkSZ
Estu 00:00 - 00:00 https://eventaservo.org/eventoj/5n3AHVxwWKo3u--s
Estu 00:00 - 00:00 https://eventaservo.org/eventoj/wzHireqQA-rMA-vD
Estu 00:00 - 00:00 https://eventaservo.org/eventoj/Mjr5kHPONof4f_pH

**Comment by shayani** [comment]
Mi jam ĝustigis la horojn de la eventoj
