### ISSUE TITLE
retadresoj: protekto kontraŭ spamo estas bone, sed eble alia solvo eblas? 

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#109]
xxx <ĉe> yahoo <punkto> com
ekz. per <code>
vidu la paĝon 
https://www.smartlabsoftware.com/howto/hide-email-spambots.htm

(propono de Lode)

**Comment by shayani** [comment]
Mi ne komprenis lian proponon. La retpoŝtadresoj jam estas kaŝitaj.

**Comment by yvesnevelsteen** [comment]
Lode ne ŝatas la aspekton de la retpoŝtadreso kiam oni ne estas ensalutinta. Laŭ li ankaŭ kiam oni ne estas ensalutinta, retpoŝtadreso estu alklakebla.

Cetere: mi ne certas ĉu la vorto "Retpoŝtadreso:" aperu entute tie, ĉar ja klaras ke temas pri tio.

![2D6EE2C0-505D-4FCB-8BE7-2B6D8BED6E60](https://user-images.githubusercontent.com/45429699/58316471-e8fec580-7e13-11e9-8c04-29d48c28fe13.jpeg)

**Comment by RobinvanderVliet** [comment]
>https://www.smartlabsoftware.com/howto/hide-email-spambots.htm

Tiaj JavaScript-aĵoj ne vere malhelpas. La robotoj de Google (kaj ankaŭ aliaj robotoj) funkciigas JavaScript-kodon, do la veraj retpoŝtadresoj tiel aperus en Google.
