### ISSUE TITLE
Kalendaro en eventa paĝo estas en la angla

### ISSUE THREAD

**Issue by picsi** [eventaservo/eventaservo#11]

**Comment by shayani** [comment]
Vi pravas. Mi serĉas kiel traduki jQuery-UI kalendaron.

**Comment by yvesnevelsteen** [comment]
Eble la solvo legeblas ĉi tie: https://stackoverflow.com/questions/494958/how-do-i-localize-the-jquery-ui-datepicker

Estas elŝutebla EO-versio en la paĝo https://github.com/jquery/jquery-ui/tree/master/ui/i18n

**Comment by shayani** [comment]
Dankon. Mi riparis ĝin per la enmeto https://github.com/eventaservo/eventaservo/commit/a93b8829ea2376372d0c1527550ab9415d453c63
