### ISSUE TITLE
[ES estraro] Evento ĝisdatiĝita -> [ES estraro] Evento ĝisdatigita

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#122]
Estas eraro en la teksto sendita al administranto(j): "ĝisdatiĝita"

**Comment by shayani** [comment]
?

**Comment by shayani** [comment]
Laŭ PIV: _"ĝisdatigi. Fari, ke io estu ĝisdata"_, do estus: 

"EventoN ĝisdatigita", laŭ vi propono, ĉu ne? Ŝajnas tre stranga...
