### ISSUE TITLE
Kalendara vido: se oni alklakas la reen-butono post kiam oni afiŝis eventon, ne aperas la antaŭa paĝo, sed la ĉefpaĝo

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#123]
Laurent Vignaud:  en kalendaro, se mi afiŝas ekz. la paĝon "septembro", kaj 
poste alklakas iun eventon, ĝi memkompreneble afiŝiĝas.
Sed kiam post legado mi uzas la butonon "unu paĝo malantaŭen" de mia 
TTT-legilo, la ekrano revenas al la paĝo "majo" (aŭ nun - mi ne 
komprenas kial - al la kartaro). Estus pli bone se re-afiŝiĝus la paĝo 
"septembro".

**Comment by shayani** [comment]
Cimo ne plu okazas.
