### ISSUE TITLE
Ĉu ekzistas bona malfermitkoda alternativo por GC

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#125]
Nikolao : Post pli ol 24 horoj informoj ne ankoraŭ ĝisdatiĝis, kaj ne plu estas modifebla en GC mem. Ĉu ne ekzistas iel eblecon forci la ĝisdatigon en ES aŭ en GC? Ĉar sen ĝisdatigo sufiĉe fidinda, mi ne povos uzi la abonon por aperigi eventojn kreitajn aŭ fakte pli ĝuste modifitajn en ES.

**Comment by shayani** [comment]
Mi fermas la Issue pro manko de aktiveco.
