### ISSUE TITLE
Kiam mi algluas eventan ligilon, aperas malĝusta dato

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#126]
![Screenshot_20190531-145105](https://user-images.githubusercontent.com/45429699/58706986-db1ce780-83b3-11e9-9ad1-6de408afb1f0.png)

**Comment by yvesnevelsteen** [comment]
Strangas ke la problemo okazas en Skype, sed ne en Facebook.

**Comment by shayani** [comment]
Vere strange. Mi kontrolos kaj forigos la ES emblemon. Nur aperos foton eventan, se ĝi ekzistas.
