### ISSUE TITLE
Okazinta evento ne aperu en ES

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#127]
Aperas en ES ke la Kunveno de La Verda Stelo finiĝos hodiaŭ, dum ĝi finiĝis hieraŭ je la 22h. Ĉu vi povas pripensi kiel malaperigi eventojn tuj post kiam ili finiĝis?

![Screenshot_20190601-090353](https://user-images.githubusercontent.com/45429699/58745095-9a24e180-844c-11e9-81c8-d352988200a4.png)

**Comment by shayani** [comment]
Mi fermas la Issue pro manko de aktiveco.
