### ISSUE TITLE
Retry later

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#128]
Okazas sufiĉe ofte ke aperas ĉi tiu ekrano, ĉu mi estas ensalutinta aŭ ne.

![E6CEC983-A792-4443-998E-6FCEB2264FA9](https://user-images.githubusercontent.com/45429699/58749412-1be53100-8486-11e9-861c-6d998348ba9f.png)

**Comment by shayani** [comment]
*Malŝaltas
