### ISSUE TITLE
Kiam mi elektas Mondo > Eŭropo, ambaŭ Kartaro kaj kalendaro bluas.

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#131]
![BC78B74F-EF2C-49BC-AD75-B330B8E0C9FC](https://user-images.githubusercontent.com/45429699/58983685-a8218c00-87d7-11e9-9a29-f0733c15fbe3.png)

**Comment by shayani** [comment]
Post la forviŝo de Turbolink, ĉu tiu situacio ankoraŭ okazas?
