### ISSUE TITLE
Kampo kun informoj/ligiloj nur por eventa administranto

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#133]
Mi organizas eventon https://eventaservo.org/eventoj/KAps4KhWGRy7Cg-w kaj por organizi ĝin estus praktike se mi povus ĉe ĝi aldoni notojn, ligilojn al retmesaĝoj ktp kiuj ne estus publikigitaj. Ĉu vi povus krei kroman enhavan kampon kiu estus nur videbla por (eventa) administranto?

**Comment by yvesnevelsteen** [comment]
Ĉu io tia?

![administraj notoj](https://user-images.githubusercontent.com/45429699/59564987-c3995c00-904d-11e9-9117-0890cc37d140.PNG)

**Comment by shayani** [comment]
Tio eblas, sendube. Mi ne komprenis ĝian utilon.

**Comment by yvesnevelsteen** [comment]
La ideo estas ke aktivulo havu la eblon konservi ĉe evento informojn kiuj ne estos publike haveblaj. Ĉar mi sentis tiun "bezonon", eble ankaŭ utilos por aliaj. Sed ne estas prioritataĵo.
