### ISSUE TITLE
Eventaj administrantoj: nomo de organizo aperu sub 'Administranto' ĉe unuopaj eventoj se ĝi ekzistas

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#135]
Nun estas iom konfuziga: aperas nur unu nomo de eventa administranto ĉe evento, dum pluraj personoj povas ŝanĝi ĝin. Ne necesas aldoni nomojn de ĉefadministrantoj (Fernando kaj Yves), sed ja tre indus aldoni la nomojn de membroj de organizo kiuj havas la rajton ŝanĝi ĝin.

**Comment by shayani** [comment]
Mi sugestas forigi la nomon de "Administranto" se evento apartenas al Organizo. Tia evento montros la organizan nomon kiel "administranto". 

Tamen, se evento se apartenas al organizo, montros la administranto kiel kutime.

Ĉu bonas?

**Comment by yvesnevelsteen** [comment]
Sonas logike.

Op zo 14 jul. 2019 18:54 schreef Fernando Shayani <notifications@github.com
