### ISSUE TITLE
Kolora teksto en konfirma mesaĝo al eventa administranto

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#139]
En la tria kaj kvara frazo estas uzata alia koloro ol nigra. Kial?
Eble ŝanĝu al nigra.

![image](https://user-images.githubusercontent.com/45429699/61209306-a5308a00-a6f9-11e9-8318-73bad6f4924d.png)

**Comment by shayani** [comment]
Kia interesaĵo! Mi provis ricevi ĝin sensukcese. 
![Captura de Tela 2019-07-19 às 15 26 02](https://user-images.githubusercontent.com/1488409/61557017-856ece00-aa39-11e9-8e85-4411ae26b698.png)

En la programkodo, ne estas diferenco de koloroj inter la frazoj:
https://github.com/eventaservo/eventaservo/blob/master/app/views/event_mailer/nova_administranto.html.haml
