### ISSUE TITLE
Kial aperas '0 venontaj' se tamen estas 3?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#146]
Vidu https://eventaservo.org/uzanto/inhye_gim

**Comment by shayani** [comment]
La algoritmo por kalkuli la eventojn en tiu paĝo estas malĝistatiĝita. Mi fermos ĉi tiun diskuton ĉar mi korektos en la nova uzanta paĝo, per la diskuto #147.
