### ISSUE TITLE
Ellabori la publikan uzanto-paĝon

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#147]
Ekzemplo konkreta: https://eventaservo.org/uzanto/inhye_gim

Mi proponas konkrete la jenon.

Por ĉiuj uzantoj de ES videbla:
- montri venontaj KAJ pasintaj eventoj, samkiel ĉe organizoj
- montri bildon (samkiel ĉe organizoj)
- aldoni kontakteblon per formularo

Nur por administrantoj:
- montri la retpoŝtadreson + butono 'kopii' por plifaciligi kaj plirapidigi la eblon kontakti la uzanton. (Se nun mi volas kontakti uzanton, mi devas traserĉi la liston https://eventaservo.org/admin/users Kopii retpoŝtadreson tie ne facilas.

Cetere:
- ne funkcias la filtrado de eventoj en la nuna uzantopaĝo

Poste Martin Rue povus aldoni la eblon ligi al la ES-uzantopaĝo de la uzantopaĝo en https://esperantujo.directory/ (mi jam priparolis tion kun li dum SES/SEP en Nitra)

**Comment by yvesnevelsteen** [comment]
Jen propono krei publikan uzantopaĝon:

https://eventaservo.org/uzanto/[nomo de la uzanto]
Ekzemple https://eventaservo.org/uzanto/fernando_maia_jr

Ĝi montru (nur por ensalutintoj!):
- profilbildon de la uzanto
- sinprezenton de la uzanto (ne deviga)
- naskiĝdaton de la uzanto (ne deviga)
- elektitajn ligilojn de la uzanto (ne deviga)
- loĝlokon de la uzanto (ne deviga)
- organizojn de la uzanto
- eventojn de la uzanto
- formularon por kontakti la uzanton. Grava: uzanto havu la eblon malŝalti tion por ne-administrantoj.

Inspiro: https://esperantujo.directory/uzanto/SJxr35BTB

**Comment by shayani** [comment]
Tio estas bona ideo. Mi planos ion similan

**Comment by shayani** [comment]
Mi fermas la Issue pro manko de aktiveco.
