### ISSUE TITLE
Konvertilo de x-igita teksto

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#149]
Relative ofte aperas x-igitaj aŭ parte x-igitaj tekstoj en priskriboj de eventoj de ES. Ne estas tio tre bela; mi foje korektas mane aŭ uzas mian kovertilon https://komputeko.net/konvertilo.php Tamen, estus bele se aperus ie en la 'Nova evento'- interfaco butono 'Konverti x-ojn al ĉapelitaj literoj'. Aŭ 'purigi/beligi tekston' - io tia.

Jen ekzemplo de tia teksto:

Malferma kluba renkontiĝo, cxi-foje en Erlangen la 3-an ĵaŭdon en la monato je la 19-a horo. Ĉiu estas bonvena.

Malferma renkontiĝo en Erlangen- ĉiuj estas bonvenaj.
Malferma kluba renkontiĝo, cxi-foje en Erlangen la 3-an ĵaŭdon en la monato je la 19-a horo. Gastoj estas ĉiam bonvena.

Pliaj informoj:
Ni kutime renkontiĝas restoracio, kie almenaŭ eblas manĝi vegetare.
esperanto.nurenbergo(ĉe)gmail.com
Cxi foje ni renkontigxas en Erlangen.

Ĉi-foje okazos en:
Moderna Barata Restoracio "Chai Roti"
Goethestraße 26
91054 Erlangen

La restoracio situas ege proksime al la cxefstacidomo en la urbocentro de Erlangen, do gxi facile atingeblas per buso au trajno. Pagenda Aŭtoparkejo "Großparkplatz" troviĝas malantau la stacidomo (rigardante de la urbocentro).

**Comment by shayani** [comment]
Mi planis fari tion ekde la komenco, automate, kiel vortaro.net faras, tamen mi ne havas la JS script. Robin, unufoje diris al mi ke li sendus la kodon al mi, sed mi ankoraŭ ne ricevis ĝin.

**Comment by shayani** [comment]
Duobligita de #326
