### ISSUE TITLE
Krei organizaĵojn por konigi kaj ĝisdatigi diversajn eventojn

### ISSUE THREAD

**Issue by shayani** [eventaservo/eventaservo#15]

**Comment by yvesnevelsteen** [comment]
Eblas jam nun listigi eventojn de kreinto. Se pluraj homoj aldonas eventojn por iu organizaĵo, utilus povi filtri je tio kaj do listigi eventojn de organizaĵo.

**Comment by yvesnevelsteen** [comment]
Indus krei sistemon de administrantoj por eventoj de organizaĵoj. Mi ekzemple aldonis ĉiujn nederlandajn eventojn pri kiuj mi scias, sed ofte mankas priskriboj kaj detaloj. Tiujn oni aldonos poste; kiam estos pli da konkretaj informoj. Estus do bone se ne nur la eventokreinto povus redakti aldonitan eventon, sed ekzemple ankaŭ elektita/indikita administranto de loka klubo aŭ alia organizaĵo.
