### ISSUE TITLE
Deziro: Eksportebleco kiel KML/KMZ

### ISSUE THREAD

**Issue by wdiestel** [eventaservo/eventaservo#153]
Mi tre ŝatas la retservon. Estus bone, se oni povus eksporti filtritan eventaron (regiono+tempo) al dosiero en formato KML/KMZ. 

Kial? Tiel oni povas importi ilin en propran Guglo-mapon kiel bazo por vojaĝplanado, ekz. poste aldonante biciklovojon aŭ trajnkonekton, privatajn vizitojn per Pasporta servo ktp.

**Comment by shayani** [comment]
Mi fermas la Issue pro manko de aktiveco.
