### ISSUE TITLE
Ne funkcias importado de Meetup-evento

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#158]
https://www.meetup.com/Esperanto-NZ/events/fdmpqyzmbpb/

aperas jena eraro sur mia ekrano

![image](https://user-images.githubusercontent.com/45429699/64168795-9db17580-ce4c-11e9-8c23-e7e3c7939bf9.png)

(Ĉi tiu paĝo ne funkcias - eventaservo.org nuntempe ne povas prilabori ĉi tiun peton)

Importado de alia evento tamen funkciis (https://www.meetup.com/Esperanto-NZ/events/hdmpqyznbdb/)

**Comment by alejandrosame** [comment]
Saluton!

Tiu ĉi cimo jam estas riparita en https://github.com/eventaservo/eventaservo/pull/160. Kiel mi diras tie, Meetup grupoj povas elekti kaŝi la adreson kaj nur montri ĝin al grupanoj. Pro tio, la importilo devas kontroli ĉu ekzistas au ne eventeja kampo. Se ĝi ne ekzistas, oni uzas la ĝeneralan adreson de la Meetup grupo.

Amike,
Alejandro

**Comment by shayani** [comment]
Aperis nova cimo. Kiam oni importas eventon, blanka paĝon aperas.

@alejandrosame, bv kontroli kio okazas.
