### ISSUE TITLE
Ĉu aldoni la eblon 'dato ankoraŭ ne konata'?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#159]
Mi organizus [eventon en oktobro](https://eventaservo.org/eventoj/B8e-rtX1eBBkGMby), sed devos ĝin prokrasti al printempo 2020. Mi tute ne scias kiam ĝi okazos, sed tamen ne volas forigi la informojn. Ĉu eblus aldoni la eblon krei eventon sen dato, kiu nur aperus en la uzantopaĝo? Aŭ do en https://eventaservo.org/eventoj tute supre.

**Comment by shayani** [comment]
Ne estas bona ideo aldoni evento sen dato. Elektu la daton kiam eble ĝi okazos kaj ŝanĝu ĝin poste.
