### ISSUE TITLE
Kiam oni pligrandigas foton, la kalendaro plu aperas.

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#16]
![053d5eb1-6322-436d-9a92-06e7f00bfeb3](https://user-images.githubusercontent.com/45429699/52503088-c938ee00-2be4-11e9-8d3b-54b9edc7c092.png)

**Comment by shayani** [comment]
🧐 eble tiu viro ne volas aperi en la foto.

Ŝajnas problemo kun Z-index.

**Comment by shayani** [comment]
Riparita per la enmeto https://github.com/eventaservo/eventaservo/commit/17e4fe23aff672862068bc1c7d7e407249710313
