### ISSUE TITLE
Ĉu aldoni bazajn datumojn ĉe organizo?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#161]
Mi pensas unuavice pri
- adreso de la sidejo
- retejo
- retpoŝtadreso
- telefonnumero

![AB9DF5A5-3828-4B34-8188-A97C418F3364](https://user-images.githubusercontent.com/45429699/64377827-9f855f80-d02b-11e9-9e23-a1e157f87518.jpeg)

**Comment by shayani** [comment]
Jes. Estas bonega ideo. Dekomence mi pensis pri tio tamen mankis tempo.
