### ISSUE TITLE
Ne eblas forigi organizon

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#162]
Mi erare kreis https://eventaservo.org/o/PEA-PL 
Ĉu vi povas forigi ĝin?

Ne ekzistas ankoraŭ la eblo forigi organizon; eble indas aldoni tion; almenaŭ por administrantoj.

**Comment by shayani** [comment]
Mi forviŝis PEA-PL kaj konsentas bona ideo aldoni eblon forviŝi organizojn.
