### ISSUE TITLE
Aldoni la eblon traserĉi organizojn

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#164]
Jam aldoniĝis tiom multaj organizoj ke indus laŭ mi.

**Comment by yvesnevelsteen** [comment]
Mi ĵus instalis iPadOs 13 kaj ial ne plu povas traserĉi la retpaĝon kie organizoj estas listigitaj. Indus do vere aldoni serĉeblon por eviti enigon de jam ekzistanta organizo.

![E4BCFC5C-D317-4813-B46E-6D75F866EC16](https://user-images.githubusercontent.com/45429699/65577081-73e2fe80-df73-11e9-83a9-77aecaa080ad.png)

**Comment by shayani** [comment]
Strage Apple malaperigi tiun serĉilon, ĉu ne?
