### ISSUE TITLE
Nomoj kaj retpoŝtadresaj videblaj

### ISSUE THREAD

**Issue by RobinvanderVliet** [eventaservo/eventaservo#165]
Kiam mi iras al la paĝo de mia propra organizo kaj rigardas la fontokodon, mi povas vidi la nomojn kaj retpoŝtadresojn de ĉiuj uzantoj de Eventa Servo. Jen ekrankopio:
![image](https://user-images.githubusercontent.com/692029/64481758-4a8c4980-d1e3-11e9-9e65-3549f5a4325d.png)

Nepre indas igi ĉi tiun paĝon pli privatec-amika. Ĉu eble eblus uzi internan identigilon anstataŭ uzi retpoŝtadreson en "value"? Tio jam solvus parton de la problemo.

**Comment by shayani** [comment]
Vi pravas @RobinvanderVliet. Mi jam trovis solvon por tio. Tre baldaŭ mi riparos tion en ES. Dankegon por sciigi min pri tio.

**Comment by yvesnevelsteen** [comment]
Ĉu solvita?

**Comment by shayani** [comment]
Ankoraŭ ne

**Comment by yvesnevelsteen** [comment]
Venis plendo: Sed, ĉu eventaservo.org kutimas publikigi retpoŝtadresojn tute neproektite? Mi vidis en la fontokodo mian mailto:andim@gmx.li , tute sen - kiel mi kutimas fari - javaskripto aŭ tiaĵoj. Mi ŝanĝos post vi igis min administranto. Sed certe multaj aliaj ne ŝatos tion. Bonŝance "(ĉe)" botoj ne povas deĉifri al "@", pri "(at)" mi jam ne certas.

**Comment by shayani** [comment]
Riparita
