### ISSUE TITLE
Pli efikigi la duobligon de eventoj

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#166]
Kiam mi duobligas eventon https://eventaservo.org/eventoj/oxGRhfmqk1_XSs8P dosieroj ne estas kopiataj. Ĉu normalas tiel? Ĉu ne indus ankaŭ kopii dosierojn? Fakte estas iom temporabe por mi tiel duobligi multajn eventojn. Aktivuloj apenaŭ faras; ili volas indiki 'ni kunvenas ĉiusemajne en sama loko kaj je sama horo, punkto fino'. Ĉu ni povas iel duonautomatigi la duobligon? Ke ekzemple dufoje jare mi sendos al vi liston kaj ke vi tion per kodo sur la servilo pli efike (pli rapide!) faras ol mi nun?

**Comment by shayani** [comment]
Jes, eblas duobligi la dosierojn aldonitajn. Tamen, kiam mi finos la ĝisdatiĝon al Rails 6, eblos aldoni la fotojn al la priskriba teksto, kaj tiel ĝi jam estos aŭtomata duobligita. Eble, pro tio, ne plu bezonos duobligi la kromajn dosierojn.
