### ISSUE TITLE
Eksporto al .ics kreas 3 eventojn por 1 plurtaga evento

### ISSUE THREAD

**Issue by hutereaus** [eventaservo/eventaservo#168]
Kiam oni eksportas 1 plurtagan eventon, la .ics dosiero enhavas 3 eventojn:
- 1 evento kun start- kaj finiĝtago
- 1 evento kun starthoro
- 1 evento kun finiĝhoro

Rezulte eksteraj kalendaraj programoj kreas 3 apartajn eventojn por 1 evento el ES.

**Comment by shayani** [comment]
Tia solvo tro poluas la semajn-vidon.
