### ISSUE TITLE
Ebleco krei eventojn, kiuj ripetiĝas dum intertempo

### ISSUE THREAD

**Issue by nicolasmaia** [eventaservo/eventaservo#17]
Estas ofta por E-kluboj kunveni ĉiumonate, ekzemple, en specifa tago aŭ en la lasta sabato. Estus utila se ES povus havi sistemon por faciligi tiun datumenigadon.

**Comment by shayani** [comment]
Tiu ĉi ideo estas interesa, tamen kiel aldoni tian funkcion al ES kaj eviti oni SPAM-igis da sistemon? 

Ekzemplo: oni povus aldoni eventon kiu okazas ĉiu tage.

Nuntempe, mi konsilas uzi la 'Duobligi eventon' butonon 👍

**Comment by yvesnevelsteen** [comment]
Estus bone krei la eblon aldoni en unu fojo plurajn datojn (ekzemple tuj por tuta jaro) kun "ŝablono" kiun organizantoj poste enhave ŝanĝu/kompletigu. Ekzemplo: en Parizo okazas kultura evento ĉiun unuan kaj trian lundon en sama loko kaj sama ejo. https://eventaservo.org/eventoj/3ut_7vg-lXr11vkB

Eventuale tiun eblon antaŭvidu komence nur por administrantoj. Ili (ni :-)) povos tiel ekzemple "apliki la logikon" 1 foje semajne/monate ktp kaj forigi esceptajn okazaĵojn kiam kunveno ne okazos (ekzemple somere aŭ dum Kristnasko).

Ni (Mi) ŝparus multe da tempo kaj ĉiam aperos informo ke io okazos en iu loko; lokaj respondeculoj nur devos kompletigi jam ekzistantajn eventojn. Tion ili laŭ mi pli facile faros ol krei novan.
