### ISSUE TITLE
Ikono-miniaturoj de organizoj: Iuj ne bone aperas 

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#173]
Kial iuj aperas (UEA) kaj aliaj ne (Frateco)?

![F4755EF2-8CF4-4504-9F2A-C052DC494AC8](https://user-images.githubusercontent.com/45429699/65023592-728e5200-d933-11e9-8252-cf9d111ec046.jpeg)

**Comment by shayani** [comment]
La ikonoj de organizoj ne plu aperas ekster la organiza paĝo
