### ISSUE TITLE
Ĉu faciligi aldonadon de nacilingvaj titoloj?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#175]
Foje al ES mi aldonas dulingvan titolon kun stelo meze, ekzemple
Esperanto lesson for beginners ☆ Esperanto-leciono por komencantoj

Mi daŭre opinias ke foje pro diversaj kialoj havas sencon mencii titolon ankaŭ en la loka lingvo. Plaĉus al mi dua titolo-linio 'Titolo en loka lingvo (ne deviga)' kiu aŭtomate kunmetus la du titolojn kun meze bela distinga stelo.

Pripensida :-)

**Comment by shayani** [comment]
Pripensenda, certe...
