### ISSUE TITLE
Konigo de organizo per Facebook Messenger kaj Telegram: bildo

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#176]
Kiam mi konigas organizon per Messenger, aperas la ĝenerala reklama bildo de ES. Ĉu eblus anstataŭi ĝin per bildo kaj priskribo de la organizo, se ĝi estas alŝutita?

![9D5ABB60-CF6B-4721-9F95-AFA270050EB5](https://user-images.githubusercontent.com/45429699/65838636-70e66600-e305-11e9-9811-9434a705f395.jpeg)

**Comment by shayani** [comment]
Oh, interesa ideo. Mi pensas ke eblas 👍

**Comment by yvesnevelsteen** [comment]
Samo okazas per Telegram

![FA09D29C-FBBA-4D1F-BFF5-FCBECF8659B8](https://user-images.githubusercontent.com/45429699/79577622-47383500-80c5-11ea-8dd6-ce59ccf570b1.jpeg)

**Comment by RobinvanderVliet** [comment]
Verŝajne ne estas tre malfacile aldoni tion, ĉar ni jam havas belajn antaŭrigardojn por eventoj.

Ekzemplo: https://eventaservo.org/e/ijk2020

![ekzempla ekrankopio de evento](https://user-images.githubusercontent.com/692029/79588549-625e7100-80d4-11ea-9441-e0e443d9609c.png)

**Comment by yvesnevelsteen** [comment]
Por Facebook jam estas en ordo; restas Telegram

**Comment by RobinvanderVliet** [comment]
Ankaŭ jam estas en ordo por Telegram:
![ekrankopio](https://user-images.githubusercontent.com/692029/79837283-75fa2800-83b1-11ea-9ffa-00f41180f2a7.png)
