### ISSUE TITLE
mallongigi kaj malangligi nomojn de URL-oj

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#178]
organizoj: **eventaservo.org/o/**[nomo de organizo] (jam estas tiel)
eventoj: **eventaservo.org/e/**[numero de la evento]
registriĝo: **eventaservo.org/r**
statistikoj: **eventaservo.org/s**
vidmaniero: **eventaservo.org/v**/[nomo de la vidmaniero]

**Comment by shayani** [comment]
Mi faris tiom krom statistikoj. Mi ne tute konsentas krei mallongigon por tio.
