### ISSUE TITLE
Ĉu okazaĵoj anstataŭ eventoj

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#179]
El lingva vidpunkto, kunvenoj kaj kursoj NE estas eventoj. 'Evento' laŭ PIV estas 'Difinita, sufiĉe grava okazaĵo'.

Sen voli ŝanĝi la nomon Eventa Servo (evidente), mi opinias ke ni ĉie en la ES-retejo uzu 'okazaĵo'-n kiam temas pri tio... Ekzemple ĉe organizoj:

![Screenshot_20191002-114630](https://user-images.githubusercontent.com/45429699/66034955-8678ad00-e50a-11e9-9358-432d83cabca1.png)

**Comment by RobinvanderVliet** [comment]
> El lingva vidpunkto, kunvenoj kaj kursoj NE estas eventoj. 'Evento' laŭ PIV estas 'Difinita, sufiĉe grava okazaĵo'.

Ĉu kunvenoj kaj kursoj ne estas "sufiĉe gravaj"? Ili ja estas "difinitaj" kaj "okazaĵoj".

**Comment by yvesnevelsteen** [comment]
Jes, vi pravas. Foje mi emas troigi.
