### ISSUE TITLE
Aperas teksto en la portugala se oni ne enigas informojn en deviga kampo

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#18]

**Comment by yvesnevelsteen** [comment]
![fea077cf-b1a1-423b-a3a7-33c3a024eda8](https://user-images.githubusercontent.com/45429699/52528087-f8c72380-2cd4-11e9-9fd9-18538d1ae665.png)

**Comment by shayani** [comment]
Dankon. Mi riparis ĝin per la enmeto https://github.com/eventaservo/eventaservo/commit/a93b8829ea2376372d0c1527550ab9415d453c63
