### ISSUE TITLE
Malnovaj informoj aperas kiam oni diskonigas eventon per Telegram

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#183]
Informoj de la evento https://eventaservo.org/eventoj/6a9b1a estas intertempe ĝisdatigita de la organizanto, sed se mi diskonigas ĝin, aperas en Telegram la originala teksto.

![0E2085EE-64C8-46B6-9892-C9DE5D592CA7](https://user-images.githubusercontent.com/45429699/67139476-f9935a80-f250-11e9-9d68-aaa9895de3ac.jpeg)

**Comment by RobinvanderVliet** [comment]
Tio estas problemo de Telegram, ne de Eventa Servo.

Telegram konservas la antaŭvidon de ligiloj tre longe en kaŝmemoro. Vi povas sendi la ligilon al la Telegram-roboto [@WebpageBot](https://t.me/WebpageBot) por ke Telegram tuj ĝisdatigu la antaŭvidon de la ligilo.
