### ISSUE TITLE
Organizo: aldoni kampon 'telefonnumero'

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#188]
Ĉe organizo mankas la kampo 'telefonnumero'. Ĉu vi povus aldoni ĝin kun bela ikono? Nun aperas ĉi tiel:

![E0E0D2B9-E448-40FF-BF27-61FE25383DCD](https://user-images.githubusercontent.com/45429699/68741503-16bc0e80-05ee-11ea-8177-6dd01d5b30ab.jpeg)

Eble indas distingi inter poŝtelefona kaj fiksa numeroj. En Francio ekzemple poŝtelefona numero komenciĝas per 06, sed tion ne ĉiam scias eksterlandanoj.

**Comment by shayani** [comment]
1ad0ec80e9c461b5b7e3254cde2002b1417a1451
