### ISSUE TITLE
Afiŝado de bildoj: foje ili ne aperas sur iPad

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#189]
Malklaras por mi kial foje ne:

![1A9F88BD-8D5D-4193-BED0-518CC45F8EB9](https://user-images.githubusercontent.com/45429699/68748551-edef4580-05fc-11ea-8149-25506f0af942.jpeg)

**Comment by shayani** [comment]
Ankaŭ al mi malklaras...
