### ISSUE TITLE
Strangaj signoj aperas ĉe paĝokapoj de retumilo

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#190]
Françoise Noireau sciigis ke foje strangaj signoj aperas supre de paĝo, ekzemple por signoj kiel '

![CFCDA663-22A9-434D-BEB7-0B106B223EC2](https://user-images.githubusercontent.com/45429699/68786310-de452080-063f-11ea-9ba2-fd26ce54a690.png)

Ĉu eblas fari ion pri tio?

Referenco: https://eventaservo.org/eventoj/UC7WU3rKKZ4MR8aa

**Comment by RobinvanderVliet** [comment]
Tio okazas, ĉar oni dufoje faras [URL-kodadon](https://en.wikipedia.org/wiki/Percent-encoding) en la fontkodo. Apostrofo iĝas "&#39;", kio montriĝas simple kiel apostrofo, tio bonas. Sed poste tio iĝas "&amp;#39;", kio montriĝas kiel "&#39;".

**Comment by shayani** [comment]
Ĉu estas io kiu ni kapablas fari pri tio aŭ ĉu mi povas fermi tiun problemon?

**Comment by yvesnevelsteen** [comment]
Verŝajne ne eblas ion fari, do mi fermas.

**Comment by RobinvanderVliet** [comment]
Eblas kaj indas solvi ĉi tiun problemon. Vidu la fontkodon ĉe: https://eventaservo.org/e/UC7WU3rKKZ4MR8aa

Ĉi tie ĝi aperas ĝuste:
`<meta content='Club d&#39;espéranto  ☆ Esperanto-Klubo' property='og:title'>`

Ĉi tie malĝuste:
`<title>Club d&amp;#39;espéranto  ☆ Esperanto-Klubo | Eventa Servo</title>`
