### ISSUE TITLE
Mapa vido: ĉu aperigi malpli multe da eventoj?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#192]
Homoj plendis al mi ke aperas tro da pingloj sur la mapo, ekzemple por ĉiusemajnaj kursoj. 

Povus esti solvo afiŝi nur la unuan venontan eventon sur la mapo se temas pri eventoj kiuj okazos en sama loko kaj havas saman titolon. Ekzemple.

**Comment by shayani** [comment]
Se Eventoj havas la saman lokon kaj titolon, aperos nur la sekvan ĉe la mapo.
