### ISSUE TITLE
Mallongigilo de eventaj retejaj adresoj

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#196]
Por krei ekz. www.eventaservo.org/luminesk5
Laŭ inspiro de www.mallonge.net

Ni atentu: FB Messenger blokas ligilojn de www.mallonge.net

![image](https://user-images.githubusercontent.com/45429699/69962205-c7db0800-150d-11ea-962b-90e985640f2e.png)

**Comment by shayani** [comment]
Mi jam planas fari tion tre baldaŭ 🙂
