### ISSUE TITLE
Rusio estas parte eŭropa kaj parte azia lando

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#20]
Estas problemo kiam oni montras superrigardon de eŭropaj eventoj: montriĝas ankaŭ tiuj de azia Rusio.

![eb45d7ac-32a3-4fba-887c-2f47b593cdc4](https://user-images.githubusercontent.com/45429699/52539994-f6240700-2d84-11e9-88d0-cdf55745816e.png)

"The other, eastern, part of the Russian Federation forms part of northern Asia, and is known as North Asia, also called Asian Russia or Siberia."

https://en.m.wikipedia.org/wiki/European_Russia

**Comment by shayani** [comment]
Kion vi sugestas? Krei landon "Asia Rusio", eble?

**Comment by yvesnevelsteen** [comment]
Mi ne scias. Indus esplori kiel aliaj retejoj traktas tiun 'problemon'.

**Comment by yvesnevelsteen** [comment]
Ĉu eblus zomi tiel ĉi se homoj elektas la mapon de Eŭropo?

![48cffcc9-b071-466c-bed2-4c1f1c6d737a](https://user-images.githubusercontent.com/45429699/52540190-253b7800-2d87-11e9-88a2-81ef1ecc36d6.png)

**Comment by RobinvanderVliet** [comment]
Mi persone ŝanĝus la landon al azia, ĉar la azia parto estas multe pli granda. Estas laŭ mi akceptebla, se la eventoj en la eŭropa parto enkalkuliĝas kiel aziaj eventoj, sed laŭ mi la malo estas apenaŭ akceptebla.

**Comment by yvesnevelsteen** [comment]
Eble ni demandu la opinion de rusoj antaŭ ol agi. Mi alparolos pri tio la redaktorojn de Revuo Esperanto, kiuj loĝas en Moskvo kaj demandos al Kiki, flandrino kies edzo estas ruso kaj kiu bonege konas la landon.

**Comment by yvesnevelsteen** [comment]
Samon validas por Turkio

**Comment by RobinvanderVliet** [comment]
> Ankaŭ por Turkio ekzistas la sama "problemo"

Ankaŭ por Egiptio, Hispanio kaj Kazaĥio. Verŝajne la plej facila solvo estas elekti tiun kontinenton, en kiu troviĝas plejparte da tera surfaco de la koncerna lando.

**Comment by yvesnevelsteen** [comment]
Mi ne certas. Laŭ Dima Ŝevĉenko la granda plimulto de la rusoj loĝas en la eŭropa parto. Povus esti tikla; enloĝantoj de Moskvo kaj Sankt-Peterburgo tute sin ne konsideras azianoj. Kiel solvi tion, mi ne vere scias. Eble indas konsideri krei "du Rusiojn": Rusio (Eŭropo) kaj Rusio (Azio). Ĉu tio kreus iujn praktikajn malfacilaĵojn?

**Comment by shayani** [comment]
Mi konsentas krei du Rusiojn. Mi ne antaŭvidas malfacilaĵojn.

**Comment by shayani** [comment]
Mi ĵus aldonis ĝin al la nuna versio.
