### ISSUE TITLE
Malstriktigi la regulojn pri mallonga organiza nomo

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#202]
ü estas iom ofta litero kaj ne estas la sola ne-ASCII-litero kiu iom oftas en nomoj de urboj. Ĉu vi povus malstriktigi la regulojn pri la mallonga nomo de organizo?

![53D49B68-824B-4461-A617-78A1B65D968A](https://user-images.githubusercontent.com/45429699/71362791-6ac7f480-2597-11ea-8c4f-f1e48adb8ce2.jpeg)

**Comment by shayani** [comment]
https://github.com/eventaservo/eventaservo/commit/ef82f42bfe31c6c2435fe4ce8d7fbd0a20345774
