### ISSUE TITLE
Ŝajnas esti problemo pri serĉado

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#203]
Ne bone funkcias kiam la serĉvorto komenciĝas per majusklo. Tio ĝenas, ĉar iPad aŭtomate majuskligas, ekzemple. Kaj ne logikas ankaŭ, ĉar Novojarsk ja komenciĝas per majuskla N.

![1B5DE547-3096-489A-8E6B-D39669120455](https://user-images.githubusercontent.com/45429699/71438289-6ca7ca00-26f5-11ea-85e7-2e9e1f23daa2.png)

**Comment by shayani** [comment]
Tio ne pravas. La serĉilo funkcias majŭskle kaj minuskle same. 
Mi opinias ke la problemo estas alia (tiel, kiel kelkfoje aperas blanka paĝo). Mi klopodas eksplori tion.
