### ISSUE TITLE
Ĉu plifaciligi la integrigon de ES en aliaj retejoj?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#205]
Mi pripensis ke ni povus ekzemple proponi al la grupo de Hameln afiŝi informojn el https://eventaservo.org/o/RB sur la paĝo https://www.esperanto.de/eo/enhavo/hameln/kalendaro

Tiucele ni povus krei "simpligitan vidon" de la retejo kiel https://eventaservo.org/o/RB/ekstera kiu aspektus ĉi tiel:

![image](https://user-images.githubusercontent.com/45429699/71768333-81663800-2f15-11ea-94d9-64229118c820.png)

La rezulto povus poste aspekti ĉi tiel:

![ratkaptista propono](https://user-images.githubusercontent.com/45429699/71768459-54feeb80-2f16-11ea-80f0-a4f1df382349.jpg)

**Comment by yvesnevelsteen** [comment]
Jam Fernando kreis solvon. Sufiĉas al la,ligilo aldoni ?iframe=jes

https://staging.eventaservo.org/o/RB?iframe=jes

Oni devas nur aldoni tion al sia retejo: 

Ekzemplo: <iframe src="https://staging.eventaservo.org/o/UEA?iframe=jes" width="100%;" height="700px;"></iframe>

**Comment by shayani** [comment]
https://github.com/eventaservo/eventaservo/wiki/Integrigo-de-organiza-paĝo-en-aliaj-retejoj
