### ISSUE TITLE
Ĉu eblus aldoni minuskligi-butonojn ĉe la titolo kaj la priskribo? (nur por administrantoj)

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#206]
Por pli facile kaj rapide minuskligi tiaĵojn...

![image](https://user-images.githubusercontent.com/45429699/71993300-272be680-3237-11ea-8d3f-0ad12253dae9.png)

**Comment by RobinvanderVliet** [comment]
Eble povus esti bona ideo malpermesi la uzadon de nur majuskloj. Ekzemple kiam iu volas afiŝi ion, oni povas kontroli, ĉu la entajpita teksto konsistas por pli ol 80 % el majusklaj, kaj en tiu okazo rifuzi la afiŝon.

**Comment by yvesnevelsteen** [comment]
Tre bona ideo! Mi tute ne sciis/pensis pri tiu eblo. Fernando antaŭe provis malpermesi ĉiujn majusklojn en titoloj, sed tio ne estas bona ideo. Robin: ĉu vi scias kiel teknike fari tion?
