### ISSUE TITLE
Google-serĉado SEO

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#207]
Kiam mi serĉas per Google je "esperanto charleroi", aperas kiel unua ligilo malnova kunveno en oktobro 2019. Ĉu iel eblus zorgi pri tio ke anstataŭe aperu ligilo al https://eventaservo.org/o/EO_Charleroi ?

(Estas nur ekzemplo, kompreneble - mi celas ĉi tion por ĉiuj serĉrezultoj)

**Comment by shayani** [comment]
Mi ŝanĝis la "sitemap" por prioritatigi la novajn eventojn kaj uzi la mallongan ligilon anstataŭ la kodon. Google bezonos kalkajn tagojn por komenci ŝanĝi ilin.
