### ISSUE TITLE
Organizoj: ĉu kunlabori kun Esperanto.net?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#209]
Ŝajne ne plu funkcias la mapo kun serĉilo sube de https://esperanto.net/eo/ Mi bedaŭras tion!

Ĉu ni kunlaboru por tie montri datumojn de Eventa Servo?

![19D8BF2B-EA9C-45D7-BA6D-615CE620553C](https://user-images.githubusercontent.com/45429699/72620798-4c5bdb80-3940-11ea-97bc-e48775f65258.png)

**Comment by shayani** [comment]
Esperanto.net povas kolekti la informoj per API, tamen mi planas baldaŭ krei Adresaron de organizoj tutmonde per ES 🙂
