### ISSUE TITLE
Okazas hodiaŭ: alia cimo aperis

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#212]
Aperas hodiaŭ 14 eventoj:

![A1E4DFD7-D4C3-440E-9ED9-A381F2383E91](https://user-images.githubusercontent.com/45429699/72685364-b663b480-3ae9-11ea-80a8-e324aa282374.png)

Kiam mi alklakas Eŭropo > Portugalio > Oporto kaj poste Mondo, aperas subite 18 eventoj...

![A7E8CF9A-1628-4C71-963D-A4A586BD8995](https://user-images.githubusercontent.com/45429699/72685398-fcb91380-3ae9-11ea-85e1-bc662aa4affa.jpeg)

![1307B2AD-BAA8-498D-ACC7-F90C3A4A34E3](https://user-images.githubusercontent.com/45429699/72685416-12c6d400-3aea-11ea-90e4-628bcf97edec.png)

**Comment by shayani** [comment]
Ŝajnas ke tiu cimo ne plu ozakas.
