### ISSUE TITLE
Eventoj kun stelo ne aperas en ES Administraĵoj (Telegram)

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#213]
Mi ĵus kreis la eventon https://eventaservo.org/e/e141a1 kaj rimarkis ke informoj pri ĝi ne aperis en la Telegram-grupo ES Administraĵoj. Mi supozas ke estas pro la stelo en la titolo, ĉu?

Teo kaj Amo ☆ Tè e amore

Estas iom ĝene, ĉar mi pli kaj pli uzas tiun stelon por dulingvigi titolojn.

**Comment by shayani** [comment]
Ankoraŭ mankas plibonigi tion, ĉar ĉiuj specialaj signoj estas aŭtomate tradukita al normalaj signoj.
