### ISSUE TITLE
Ne eblas importi ĉi tiun Meetup-eventon: HTTP ERROR 500

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#218]
https://www.meetup.com/CAFE-CROISSANTS-ET-ESPERANTO/events/268316024/

**Comment by shayani** [comment]
Mi kaŝis la ligilon al impotado de Meetups ĝis kiam Alejandro (aŭ aliulo) povas ripari kaj krei test-kodon pri ĝi. https://github.com/eventaservo/eventaservo/commit/ae7494d7246b612bde63c9fb59e14bd928c3d231
