### ISSUE TITLE
Varbado por ES

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#226]
Laŭ mi logike/inde estus aldoni ligilon https://eventaservo.org/j/2020 supre de https://revuoesperanto.org/eventoj kun eta enkonduko pri Eventa Servo.

Dima de Revuo Esperanto konsentas: Bone, ni faros. Morgaŭ-postmorgaŭ. Se ne, bv. memorigi.

**Comment by shayani** [comment]
Li aldonis ligilon al la tuta ES en tiu paĝo 👍
