### ISSUE TITLE
Abonoj al landaj kalendaroj: nova teksto. "Malabonitu" ne estas bona Esperanto

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#23]
Saluton

Vi nun abonas la landan kalendaron de Nederlando. Ĉiufoje kiam iu aldonos novan eventon kiu okazos en ĉi tiu lando, vi ricevos pri tio retmesaĝon.

Se vi ne plu volas ricevi informojn pri novaj eventoj en Nederlando, malabonu per ĉi tiu ligilo:
https://eventaservo.org/sciigo/FYLIYdiF_92sKZVp/forigu

_______________________________________
Mesaĝo aŭtomate sendita de Eventa Servo
https://eventaservo.org

**Comment by shayani** [comment]
https://github.com/eventaservo/eventaservo/commit/b33bf49193fcdb86955818398c66de293991b773
