### ISSUE TITLE
Urbo/loko: decidota

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#231]
Foje organizantoj decidis pri dato kaj lando, sed ne pri la ekzakta urbo/loko. Tial nun aperas en ES ĉe Pollando la urbo 'Decidota'.

![image](https://user-images.githubusercontent.com/45429699/75860650-7be57b00-5dfc-11ea-93de-76e4fcb205b2.png)

'Decidota' tamen ne estas urbo/loko :-) Ĉu vi havas proponon kiel solvi tion?

**Comment by shayani** [comment]
Ho, tio estas vera tikla demando. Mi pensas ke ni devas kontroli mane tiajn situaciojn.

**Comment by yvesnevelsteen** [comment]
Eble provizore ni metu 'Decidota' inter krampoj.

![image](https://user-images.githubusercontent.com/45429699/75875325-c32b3600-5e13-11ea-9dfb-e6539a699f06.png)

**Comment by shayani** [comment]
Estas bona solvo 👍
