### ISSUE TITLE
Kunvenoj en UEA Facila: montri nur internaciajn tie

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#232]
Mi skribis al Tim Owen: "Ĉu vi povas ŝanĝi https://uea.facila.org/kunvenoj/ tiel ke aperos tie nur internaciaj eventoj?"

Tim respondis jene:

ne, ne eblas, ĉar la API ne disdonas informon pri tio. ekzemple, hodiaŭ okazos internacia kunveno en Valencio. alklakante "internaciaj eventoj" ĉe ES montras ĝin. sed rigardu la informojn, kiujn donas al API:

    {
        "uuid": "ed6f594c-2b83-4648-ba8d-58d7b92c6626",
        "kodo": "d63624",
        "titolo": "Internacia Semajna Seminario pri UNESKO-Kuriero",
        "priskribo": "Pridiskutado pri temoj el la revuo de Unesko.  ",
        "enhavo": null,
        "komenca_dato": "2020-03-08",
        "fina_dato": "2020-03-14",
        "retpaĝo": null,
        "retpoŝtadreso": "keefeinchina@gmail.com",
        "organizoj": [
            "Grupo Esperanto Valencia"
        ],
        "reta": false,
        "loko": {
            "adreso": "Sidejo de la Grupo-Esperanto de Valencio, Peris i Valero 96",
            "urbo": "Valencia",
            "lando": "Hispanio",
            "landokodo": "es",
            "kontinento": "Eŭropo",
            "latitudo": 39.4591053,
            "longitudo": -0.3700357
        },
        "administranto": "Dennis Keefe"
    },

estas nenio en ĝi pri la event-speco. bezonatas ekzemple "speco: internacia", "speco: loka" por povi tiri unu specon disde la aliaj.

-> ĉu vi povas aldoni tiun informon al la API?

**Comment by shayani** [comment]
Mi aldonis SPECOJ al API. Bonvolu informi TIM
