### ISSUE TITLE
Nuligo de eventoj

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#235]
Se evento ne okazas (ekzemple nun oftas pro la kronviruso, mi aldonas majuskle 'NULIGITA'.
Ĉu tio estas bona solvo aŭ ĉu ni bezonas ion alian?

![image](https://user-images.githubusercontent.com/45429699/76338704-5de6b180-62f9-11ea-9a56-ee478765a0c6.png)

**Comment by RobinvanderVliet** [comment]
Eble povus esti elektobutono en la eventoj-agordoj, per kiu oni povas indiki ĉu evento estas nuligita.

**Comment by shayani** [comment]
Nuligitaj eventoj estas maloftaj. Ne valoras la penon, nuntempe, klopodi por fari tiun funkcion.

La teksto, kiel Iveso sugestis, sufiĉas, laŭ mi 👍
