### ISSUE TITLE
Afiŝi longan nomon de administranto(j)

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#240]
Pro la kronviruso, okazas pli kaj pli da retkunsidoj. Ne ĉiam klaras kiu organizas ilin. Tial estus laŭ mi bone, afiŝi la longan nomon de la administranto(j) anstataŭ la "foje neniondiran" mallongigon.

![C6396FD4-F081-4F86-81F1-63F2794E36AF](https://user-images.githubusercontent.com/45429699/77514391-0d359380-6e77-11ea-9ea4-74e1ed02b834.jpeg)

**Comment by shayani** [comment]
df614eabfb232342d46c5d04a6a4eda63353aecf
