### ISSUE TITLE
Ĉu emfazi la butonon "Aldoni eventon"?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#241]
Przemyslaw Wierzbowski sugestis fari la butonon "Aldoni eventon" iom pli videbla, eble iel emfazita.

![1DE169CC-CFDE-48C2-8214-FA09A2C13E32](https://user-images.githubusercontent.com/45429699/77539710-1ab44300-6ea2-11ea-8146-704774fffd25.jpeg)

**Comment by RobinvanderVliet** [comment]
@yvesnevelsteen Ĉu pli bonas nun? Ĉu ĉi tiu problemo povas esti fermita?

**Comment by yvesnevelsteen** [comment]
Tre bone!
