### ISSUE TITLE
Nefunkciantaj bildoj sur la mapo

### ISSUE THREAD

**Issue by RobinvanderVliet** [eventaservo/eventaservo#243]
Aperas kelkaj nefunkciantaj bildoj sur la mapo. Vidu la ekrankopion.

![ekrankopio](https://user-images.githubusercontent.com/692029/77643806-4c8bdf00-6f60-11ea-944c-cfceb4f4db74.png)

**Comment by shayani** [comment]
Strange. Eble pro la ĝistatiĝo de Webpack. Mi kontrolos "ASAP".
