### ISSUE TITLE
Reta urbo -> Reta kunveno

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#248]
Ĉu ne ŝanĝindas tio? Estus pli logika nomo...

![image](https://user-images.githubusercontent.com/45429699/78671100-1bf06180-78df-11ea-929b-f2796aaec3c9.png)

**Comment by RobinvanderVliet** [comment]
Eble estu "Reta evento" aŭ simple "Reta". "Reta urbo" laŭ mi ne sencas.
