### ISSUE TITLE
Reta eventoj ne aperu en la jar-superrigardo

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#251]
Laŭ mi, en la listo https://eventaservo.org/j/2020 (Internacia kalendaro) ne aperu retaj eventoj. Ĉu eblas ŝanĝi tion?

**Comment by shayani** [comment]
Ĉu nek internaciaj retaj eventoj? Kiel ni filtros tiajn?

**Comment by yvesnevelsteen** [comment]
Laŭ mi en tiu listo nur aperu ĉeestaj eventoj, do internaciaj eventoj, sed ne retaj.

**Comment by shayani** [comment]
Eble UK105 fariĝos reta. Ĉu li ne aperu? Imagu tiajn situaciojn, ĉar ni NE devas krei esceptojn. Programe, esceptoj estas cim-kreadilo.

**Comment by yvesnevelsteen** [comment]
Malfacilas!

**Propono 1**: ni nur aperigu en tiu listo plurtagaj internaciaj eventoj. Sed tiam ekzemple ne aperos en ĝi la Malferma Tago de UEA; ne estas ideala.

**Propono 2**: retaj eventoj aperu en tiu listo nur kiam ili estas plurtagaj.

Se ni faras nenion, aperos en tiu listo ege multaj retaj eventoj, ĉar ĉiuj estas internaciaj. Tio laŭ mi ne estas la celo de tiu listo.

![image](https://user-images.githubusercontent.com/45429699/78982481-83e2ba00-7b22-11ea-8021-01ec2667d375.png)

**Comment by shayani** [comment]
Mi malaperigos ĉiujn retajn eventojn el tiu listo. Poste ni pli bone diskutos kiel solvi tion.

**Comment by shayani** [comment]
d73294c518d6472d8021c830eb942ff99fd5c631
