### ISSUE TITLE
Statistikoj pri neretaj kaj retaj eventoj

### ISSUE THREAD

**Issue by RobinvanderVliet** [eventaservo/eventaservo#259]
Eble povus esti interese aldoni al la [paĝo kun statistikoj](https://eventaservo.org/statistikoj) diagramon, kiu montras la kvanton de neretaj kaj retaj eventoj. Povus esti interese vidi la ŝanĝojn, aparte nun kun la kronvirusa krizo.

Jen rapide desegnita ekzemplo:
![ekzempla bildo](https://user-images.githubusercontent.com/692029/79639413-ee7f9f80-818b-11ea-8c2c-5e00ec1e6f57.png)
(blua = neretaj eventoj, ruĝa = retaj eventoj)

**Comment by shayani** [comment]
Mi programis tion. Estas interesa statistiko, tamen ne "procente", ĉar ĝi estos 100% nun. Vidu la statistikan paĝon ;)
