### ISSUE TITLE
Diskonigilo: ĉu pligrandigi la butonojn?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#26]
Mi rimarkas ke en praktiko tiuj butonoj estas iom malgrandaj, malfacilas alklaki ilin. 
Ĉu ne estus bona ideo fari ilin duoble pli grande?

![f6ffc742-db6c-4e9e-bc30-12b07a8754c5](https://user-images.githubusercontent.com/45429699/52622898-3da4b300-2eab-11e9-9738-9177bd58c0ad.png)

**Comment by shayani** [comment]
https://github.com/eventaservo/eventaservo/commit/9120e2f799a312210a128a6cc020e855bacc6c93
