### ISSUE TITLE
Vidmaniero Listo: ankaŭ tie montri nuligitajn eventojn ruĝe kaj trastrekite

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#266]
Vidmaniero Listo (Kalendaro > Semajno):

![923D4907-4EAC-4811-B68C-7606FF6740B3](https://user-images.githubusercontent.com/45429699/79701310-50c7c580-829c-11ea-9694-b416604ad605.jpeg)

**Comment by shayani** [comment]
FullCalendar.js, kiu estas la ilo por krei tiun kalendaron, ne kapabligas min trastrekitigi la eventan tekston. Mi sugestas malaperigi la nuligitajn eventojn el tiu kalendaro. Jen ekzemplo:
![Captura de Tela 2020-04-20 às 11 11 59](https://user-images.githubusercontent.com/1488409/79761482-e8a6cd00-82f7-11ea-8d08-86810b461f52.png)

**Comment by yvesnevelsteen** [comment]
Jes, ne montri ilin en la kalendara vido estas bona solvo.
