### ISSUE TITLE
Retaj eventoj: ĉu ligi rekte defaŭlte al la semajna kalendara vido?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#267]
Venis demando, ĉu eblus defaŭlte malfermi la kalendaran vidon por retaj eventoj, kiam oni entajpas www.eventaservo.org/reta pro tio, ke gravas la horo de komenciĝo por tiaj eventoj. Ĉu eblus tio? Ĉu ankaŭ aŭtomate montri tiun vidon, kiam uzanto alklakas 'reta'? Eble logikus.

![E3173474-4998-4497-A75D-E4DC7C086B8E](https://user-images.githubusercontent.com/45429699/79770541-d8a9e000-832d-11ea-9234-f0a4b3b6c28e.jpeg)

**Comment by shayani** [comment]
Mi ne taksas ĝin bona ideo. 

Baldaŭ mi plibonigos la kardojn kaj enmetos en ĝi la komencan horon.
