### ISSUE TITLE
Semajno vido estas tre malrapida

### ISSUE THREAD

**Issue by RobinvanderVliet** [eventaservo/eventaservo#269]
La semajna vido estas ege malrapida: https://eventaservo.org/v/kalendaro
Ĉi tio okazas, ĉar la dosiero events.json bezonas 5 sekundojn por plene ŝargiĝi. Aspektis al mi unue kvazaŭ la paĝo ne funkcias, do mi provis plurfoje reŝargi la paĝon.

Ial en https://eventaservo.org/events.json?start=2020-04-21&end=2020-04-28 aperas 4347 eventoj, plejparte ekster la intervalo 2020-04-21 kaj 2020-04-28. Ŝajne tiu intervalo ne funkcias.

**Comment by shayani** [comment]
Mi kontrolos tion 👍

**Comment by shayani** [comment]
Multe pli rapida nun. Dankon @RobinvanderVliet pro la "tip".
