### ISSUE TITLE
Aldono de evento: URL aŭ retpoŝtadreso estu deviga kampo

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#27]
Ekzemplo de evento sen kontakteblo:
https://eventaservo.org/eventoj/TrWems3jUYWhJgHL

**Comment by shayani** [comment]
Mia propono: se la kreanto ne aldonas retpoŝtadreson, sia propran estos aŭtomate aldonita al la evento.
Retpaĝo daŭros nedevida.

Ĉu bonas?

**Comment by RobinvanderVliet** [comment]
> Mia propono: se la kreanto ne aldonas retpoŝtadreson, sia propran estos aŭtomate aldonita al la evento.
> Retpaĝo daŭros nedevida.
> 
> Ĉu bonas?

Ne vere. Kelkfoje mi aldonis eventojn, kiujn mi ne mem organizas, kaj mi ne volas, ke homoj kontaktu min per demandoj.

Eble devigu, ke estu almenaŭ retpoŝtadreso aŭ retpaĝo.

**Comment by shayani** [comment]
https://github.com/eventaservo/eventaservo/commit/b98da2b48d896871153057a2db92375af6ddc4df
