### ISSUE TITLE
Semajna vido: eta problemo en poŝtelefono + uskleca unuecigo

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#270]
1) 'Hodiaŭ' ne aperas en sama linio kiel Semajno kaj Monato. Ĉu eblus solvi tion?
2) 'Hodiaŭ' estu kun majusklo

![A244EEF6-2CCE-4AD4-9ED0-EF8F8FDFD700](https://user-images.githubusercontent.com/45429699/79951294-b7093f80-8478-11ea-8499-f4264b145a07.png)

**Comment by shayani** [comment]
Bedaŭrinde ne pro limeco de Fullcalendar.
Tamen tiu situacio dependas de la grandeco de la ekrano.
