### ISSUE TITLE
Hodiaŭaj eventoj nur en la unua paĝo

### ISSUE THREAD

**Issue by shayani** [eventaservo/eventaservo#274]
Jen komento de amiko kaj sugesto :

_Mi ofte vizitas vian kalendaron por sciiĝi pri eventualaj interesaj 
retaj kunvenoj. Mi konsultas ĝin per la poŝtelefono kaj mi rimarkis ion 
maloportunan : post kiam mi vidis la hodiaŭajn aranĝojn, mi legas la 
afiŝojn de la sekvantaj tagoj kaj kiam mi volas afiŝi plian paĝon da 
afiŝoj, mi devas denove relegi ĉiujn la hodiaŭajn eventojn ! do por ĉiu 
sekva paĝo mi devas tiri plurajn ekranojn supren por legi la sekvon de 
la informoj kiuj interesas min. Jen mia sugesto : oni vidu la hodiaŭajn 
eventojn nur sur la unua paĝo de la eventoj, ne sur la sekvaj, aŭ oni 
povu senfine tiri ekranon supren kaj aŭtomate legi la sekvantajn afiŝojn 
(senbezone elekti paĝnumeron)._

**Comment by yvesnevelsteen** [comment]
Mi konsentas kun via amiko.
