### ISSUE TITLE
Mesaĝo 'Nova evento aldoniĝis': ĉu minuskligi la titolon?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#28]
HungaroMania iĝas HUNGAROMANIA en la mesaĝo. Mi ne bone komprenas kial tiu titolo estu majuskle. 

Sufiĉas laŭ mi afiŝi la titolon grande, blue kaj substrekita por emfazi ke temas pri alklakebla ligilo.

**Comment by shayani** [comment]
https://github.com/eventaservo/eventaservo/commit/ac82b6b9b9e5a61645eaedc808f50495d0cd9839
