### ISSUE TITLE
Ligi retan eventon al lando

### ISSUE THREAD

**Issue by RobinvanderVliet** [eventaservo/eventaservo#284]
Kelkfoje retaj eventoj estas tamen ligitaj al iu lando. Estus bone, se eblus (nedevige) aldoni landon al reta evento.

Verŝajne necesas por tio datumbaza ŝanĝo: nun oni konservas "Reta" en la kolumno por lando, por konservi ĉu evento estas reta. Estus bone aldoni datumbazan kolumnon, kiu specife estas por konservi, ĉu evento estas reta aŭ ne.

**Comment by shayani** [comment]
Mi daŭre pensas pri tio. Kiu "lando" oni elektus se la evento estas vere internacia, kiel UK, Paralele Universo, ktp?

**Comment by RobinvanderVliet** [comment]
Tiam oni ne elektus la landon. La eblo elekti landon por reta evento devus esti nedeviga, laŭ mia opinio.

**Comment by shayani** [comment]
Elekti landon estas ĉiam deviga. Oni devas elekti almenaŭ "Reta lando" kiam ĝi estas universa evento.

Do, mi planos kiel fari tion...
