### ISSUE TITLE
Mesaĝo aperas, kiu ne aperu

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#285]
Strange; aperas ĉi tiu mesaĝo kiam mi aliras la retejon https://eventaservo.org/vido/kalendaro

![B2645513-1E97-4F44-944D-9836022FD094](https://user-images.githubusercontent.com/45429699/80915055-d2fdc280-8d4f-11ea-9f46-3b26bc2f8d69.jpeg)

**Comment by shayani** [comment]
Mi kontrolis kaj konstatis ke neniam ni uzis `/vido/xxx`. La ĝustaj adresoj estas:

`/v/kalendaro` aŭ `/vidmaniero/kalendaro`
