### ISSUE TITLE
Aldono de evento-skemo al ĉiu paĝo pri evento

### ISSUE THREAD

**Issue by RobinvanderVliet** [eventaservo/eventaservo#286]
Mi lastatempe iom esploris kiel funkcias schema.org. Mi trovis la jenajn du fontojn:
* https://schema.org/Event
* https://developers.google.com/search/docs/data-types/event

Estus bone, se ni povus aldoni tion al ĉiu paĝo pri evento. Estas relative simpla JSON-kodo, kiun ni povas generi per skripto. Jen ekzemplo por https://eventaservo.org/e/UK106:

```
<script type="application/ld+json">
{
	"@context": "https://schema.org/",
	"@type": "Event",
	"name": "106-a Universala Kongreso",
	"description": "La 106-a Universala Kongreso de Esperanto (UK) okazos de la 17-a ĝis la 24-a de julio 2021 en Belfasto (Nord-Irlando).",
	"inLanguage": "eo",
	"url": "https://eventaservo.org/e/UK106",
	"startDate": "2021-07-17",
	"endDate": "2021-07-24",
	"eventStatus": "https://schema.org/EventScheduled",
	"eventAttendanceMode": "https://schema.org/OfflineEventAttendanceMode",
	"organizer": {
		"@type": "Organization",
		"name": "Universala Esperanto-Asocio",
		"url": "https://uea.org/"
	}
}
</script>
```

(Ĉi tiu kodo estas aldoninda en la HTML-etikedo <head>.)

* `eventStatus` estu normale `EventScheduled`, sed se temas pri nuligita evento, ĝi estu `EventCancelled`.
* `eventAttendanceMode` estu normale `OfflineEventAttendanceMode`, sed se temas pri enreta evento, ĝi estu `OnlineEventAttendanceMode`.

**Comment by shayani** [comment]
Robin, mi programis tion. Jen ekzemplo de vera evento.

```
<script type="application/ld+json">
{
	"@context": "https://schema.org/",
	"@type": "Event",
	"name": "✅ EBGa virtuala kunveno (Ĉiuj bonvenaj)",
	"description": "Ni organizas retajn kunvenoj malfermitaj al ĉiuj Esperantistoj enlandaj aŭ eksterlandaj",
	"inLanguage": "eo",
	"url": "https://devel.eventaservo.org:3000/e/ae558a",
	"startDate": "2020-06-03",
	"endDate": "2020-06-03",
	"eventAttendanceMode": "https://schema.org/OfflineEventAttendanceMode",
    "organizer": {
      "@type": "Organization",
      "name": "Esperantista Brusela Grupo",
      "url": "https://devel.eventaservo.org:3000/o/EBG"
    }
}
</script>
```

Mi ne trovis sufiĉajn ekzemplos rete por kontroli ĉu ĝi estas ĝusta. Kion vi opinias?
