### ISSUE TITLE
Ĉu proponi helpon al kreantoj kaj administrantoj de retejoj afiŝi eventojn per iframe aŭ widget?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#29]
Yves montris ES, sed ili demandas "kiel praktike montri nur la aktivecojn de Loveno". Eble ES povas proponi ekzemplon de kodo en sia retejo por faciligi tiajn aferojn. Kun iframe aŭ io simila.

**Comment by JabieroKubo** [comment]
Tio ŝajnas malfacile programebla sed multege alportus trafikon al ES kaj videbligos ĝin en multaj naciaj e-retejoj... mi pretus ekzemple aldoni ion tian por mia landa retejo, mia propra blogo kaj paĝo!

**Comment by axel584** [comment]
Ankaŭ mi ŝatus fari tion :) do, ĉiuj informoj por fari tion bonvenas :)

**Comment by shayani** [comment]
Mi fermas la Issue pro manko de aktiveco.
