### ISSUE TITLE
Twitter-konto

### ISSUE THREAD

**Issue by XanderLeaDaren** [eventaservo/eventaservo#297]
Estus bela komunika reklamo ke Twitter-konto rilate al la servilo aŭtomate anoncu pri eventoj.

**Comment by shayani** [comment]
@yvesnevelsteen kion vi opinias?

**Comment by yvesnevelsteen** [comment]
Jes! Se eblas aŭtomatigi tion, mi tre favoras.
Por fari tion permane, mankas tempo.

**Comment by XanderLeaDaren** [comment]
Mi scias ke el RSS-fluo per https://dlvrit.com/ eblas aŭtomate afiŝi pepaĵojn (vd. ekz. @LaBaltaOndo, @PolaRetradio kaj @ERetradio).

Laŭ mia kompreno, temas do pri nura kreado de xml-dosiero el la datumoj de la retejo.
Tio verŝajne estos facila, ĉu ne?

**Comment by RobinvanderVliet** [comment]
Mi uzas ifttt.com por la jenaj Telegram-kanaloj:
- https://t.me/TubaroAperu
- https://t.me/EsperantoReddit
- https://t.me/laEvildea

Ankaŭ eblas afiŝi al Twitter per IFTTT.
