### ISSUE TITLE
Ĉu pravaj sugestoj?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#299]
![image](https://user-images.githubusercontent.com/45429699/85288543-32499a80-b496-11ea-8b2c-cb8301c8f7e5.png)

**Comment by shayani** [comment]
Mi aldonos 🖥  al la redakta paĝo, tamen, bedaŭrinde, 🖥  estas "emoji" kaj ĝi ne havas ŝaltitan komputilon.
