### ISSUE TITLE
Ĉu faciligi la aldonadon de bildoj ĉe la teksto anstataŭ kiel aparte alŝutita dosiero?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#30]
Mi iom eksperimentis kaj opinias ke aspektas multe pli bele bildo ĉe la teksto kiel ĉi-sube. Sed necesas iom "misuzi" la sistemon. Ĉu antaŭvidi pliajn enpaĝigeblojn?

![710b8a10-d8b2-40d7-9f24-9d2f5b8280f9](https://user-images.githubusercontent.com/45429699/52658180-b4b56800-2efa-11e9-80bf-e7fdf87eb950.png)

**Comment by shayani** [comment]
Jes, mi planas tion. Mi atendas Rails v6.0 kiu pretiĝos en Aprilo 2019. Per ĝi mi kapablos fari tion pli facile.
