### ISSUE TITLE
Registriĝi (kaj ensaluti) per kromaj servoj (Google, Apple, Amikumu)

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#306]
Chuck Smith proponas aldoni kromajn eblojn registriĝi: ankaŭ per Amikumu kaj Apple.
Ĉu io tia eblas? ni kunlaboru kun Chuck.

**Comment by shayani** [comment]
Jes, eblas. Per Google mi jam havas ideon kiel fari. Per Amikumu kaj Apple, ankoraŭ plia esploro necesas.
