### ISSUE TITLE
Aldoni la eblon aldoni dosierojn al organizoj

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#308]
Didier Janot: Mi provis alŝuti PDF-dosieron al organizo sed ne sukcesis. Alŝuti al eventoj eblas per la dekstra kadro, sed tiu kadro mankas por organizoj. Ĉu ekzistas kialo? Povus esti utile aldoni informon pri organizo je PDF-formato…

**Comment by shayani** [comment]
Same kiel #314
