### ISSUE TITLE
Ĉu krei 2 novajn servojn 'prelegservo' kaj 'kursoservo'? 

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#309]
mi multe uzis vian eventaservon en la lastaj tagoj kaj semajnoj, ĝi vere bone funkcias kaj mi volas gratuli vin kaj danki vin.

okaze de VEKI ni venis al alia eblo, alia bezono.

nia sperto montris, ke miaj prelegoj ekzemple, ĉiun semajnon, kun niaj iranaj amikoj, havis grandan sukceson. Homoj el aliaj mondopartoj povis ekscii pri ili kaj partopreni.  Ĉu ni povus evoluigi tion al pli vasta tia kampanjo?

estu du novaj servoj:
prelegservo
kursoservo

estu listo de haveblaj prelegantoj / instruistoj
la kluboj, lernejoj, E-o-centroj, povus iri tien por trovi preleganton / instruistoj por siaj kursoj
iu borsejo, iu interŝanĝo de informoj pri prelegtemoj, prelegantoj, kaj ili disponebla tempo.
la fina ideo estas, ke retaj prelegoj, kursoj, oftiĝu tra la tuta jaro.

cele al tio mi jam publikigis la liston de miaj prelegoj.
https://mirejo3.blogspot.com/2019/11/la-prelegoj-de-mirejo.html
ĉiu disponebla preleganto povus publikigi tian liston kaj aldoni tempospacojn.

bv komenti.

elkore

Mireille Grosjean
prezidanto de ILEI

**Comment by shayani** [comment]
Tio estas interesa ideo. Indas pensi serioze pri ĝi 👍
