### ISSUE TITLE
Atentigi aldoninton de evento pri eraro aŭ plibonigeblo

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#31]
Uzanto https://eventaservo.org/uzanto/andrea_ aldonis kelkajn eventojn en Liono - Francio. Ŝi aldonis ilin indikante la urbon "Lyon". Mi ŝatus proponi al ŝi ŝanĝi tion kaj anstataŭe uzi la Esperantan nomon Liono, sed ne eblas nun kontakti uzantojn. Estus bone aldoni tiun eblon. Evidente ja necesos bone protekti tion kontraŭ trudistoj.

**Comment by shayani** [comment]
Per la enmeto https://github.com/eventaservo/eventaservo/commit/07ed8cca447a2d11f5e5df2fa6a86b979bb265cc, oni ne plu kapablos krei novan urbon kun spacoj post ĝi.

**Comment by JabieroKubo** [comment]
ĉu eblos ke pli ol 1 uzanto povu ŝanĝi/modifi eventon! Ebla onta funkcio.

**Comment by shayani** [comment]
> ĉu eblos ke pli ol 1 uzanto povu ŝanĝi/modifi eventon! Ebla onta funkcio.

Jes, baldaŭ eblos ke "superrigardantoj" korektos eventojn ;)
