### ISSUE TITLE
Ĉu prezenti la paĝo-posedanton pli diskrete?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#312]
Venis kritiko pri la emblemoj de UEA kaj TEJO supre de la retejo de Eventa Servo. 

"paĝo-posedanton oni povas prezenti diskrete en la piedo aŭ kolofono, ĉu ne 🙂"

Ĉu ŝanĝi tion? Mi persone favoras movi la du emblemojn al la paĝo https://eventaservo.org/prie

![DEFAE5DB-110A-48F8-B94D-0D750972035C](https://user-images.githubusercontent.com/45429699/90233094-e07e1a80-de1d-11ea-8fed-75a5a01cf351.jpeg)

**Comment by shayani** [comment]
Ambaŭ emblemoj jam estas ĉe prie. UEA emblemo, laŭ mi, devas resti ĉe la ĉefpaĝo por ke ĝi aspektos fidinda al la uzanto.
Mi favoras montri, ĉe la ĉefpaĝo, nur la emblemo de UEA. Tejo povas esti nur en Prie.
En la sama loko kie estas Tejo nun, mi povas meti la serĉil-signon.
