### ISSUE TITLE
Tro ofte oni devas ensaluti: ĉu ŝanĝi la agordoj?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#32]
Mi aldonis plurajn eventojn lastatempe kaj konstatis ke mi devas minimume unufoje tage ensaluti, kvankam mi uzas la saman retumilon sur la sama iPad. Ĉu eblus ŝanĝi la agordojn kaj memori miajn ensalutilojn pli longe? (Ekzemple semajnon aŭ monaton)

**Comment by shayani** [comment]
Mi ne ofte ensalutas. Estas strange ke tio okazas kun vi 🤔

Ni ŝanĝis kelkajn agordojn de Devise per la enmeto https://github.com/eventaservo/eventaservo/commit/f0b76de8ec1fbb499b5f8eb549a6b788a2cf37d2. Mi pensas ke vi ne plu ofte ensalutos. 👍

**Comment by yvesnevelsteen** [comment]
Mi informtenos vin. Nur en iPad estas tiel.

**Comment by shayani** [comment]
> Mi informtenos vin. Nur en iPad estas tiel.

Ĉu iPad forviŝas kuketojn pli rapide?

**Comment by shayani** [comment]
Mi pensas ke mi trivos solvon cd6035d6d762bc49871bbab71bcaecb3e6c09fd1
