### ISSUE TITLE
Malebligi alŝuti bildojn en dosierformo kiujn ni ne akceptas

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#321]
Uzanto raportis: 
mi volis ŝanĝi emblemon de Esperantista Klubo Brno. Mi provis anstaatŭigi la ekzistantan emblemon per nova. Mi provis alŝuti emblemon en formo svg. Tio nesukcesis, aperis paĝo "Oh! Eraro okazis!". Eble vi ne subtenas bildetojn en formato svg.
Mi opinias, ke la aplikaĵo devus rifuzi dosierojn de nesubtenataj formoj.

-> ni prave rifuzu tiajn bildojn. Ne aperu "Oh! Eraro okazis!", sed "Vi ne rajtas alŝuti ĉi tian bildon. Bonvolu elekti bildon en dosierformo XYZ. Reiri al la antaŭa fenesto" - io tia.

**Comment by shayani** [comment]
Nur .GIF, .PNG kaj .JPG estas permita nun.
