### ISSUE TITLE
Aboni la tutan kalendaron per iCal

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#327]
Eblas aboni landojn kaj organizojn, sed ĉu ankaŭ rekte la tutan kalendaron? Supozeble jes. Mi ne scias kiel fari tion. Eble aldonu informojn al la paĝo https://eventaservo.org/prie

"Por aboni la tutan kalendaron per ICS", uzu ĉi tiun ligilon: xyz"

![0D7F1DA5-92F8-47FC-95A4-D2D109333573](https://user-images.githubusercontent.com/45429699/102111375-968e5b00-3e36-11eb-94cf-4c43ea675826.jpeg)

**Comment by shayani** [comment]
Ne eblas aboni la tutan kalendaron, ĉar ĝi estos tro granda kaj sennecesa. Oni povas aboni landan, organizan ou retan kalendaron.
