### ISSUE TITLE
Eblas nur serĉi sur la ĉefpaĝo : kial?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#33]
Se homoj per iu ligilo rekte iras al subpaĝo, ili ne povas serĉi, krom se ili unue iras al la ĉefpaĝo. Ĉu ne indus ebligi tion sur ĉiu paĝo?
![426e1980-3286-41b0-855f-683e0b32bef4](https://user-images.githubusercontent.com/45429699/52787061-070e9a00-305d-11e9-8432-11927ad79a9a.jpeg)

**Comment by shayani** [comment]
Jam delonge farita ;)
