### ISSUE TITLE
Se mi per tabo iras de la Urbo al Lando, mi ne povas ekserĉi landon ĝin tajpante.

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#333]
Antaŭe tio ja funkciis.

La cimo aperas ĉe organizoj kaj eventoj.

![image](https://user-images.githubusercontent.com/45429699/104934355-52005d00-59aa-11eb-82cb-d2a074a05336.png)

**Comment by shayani** [comment]
Mi ne komprenis. Kio estas la cimo?

**Comment by shayani** [comment]
Bezonas unue tajpi "space" por malfermi la liston.

**Comment by shayani** [comment]
Same de #293
