### ISSUE TITLE
Mi ne plu povas alklaki mailto-ligilon

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#334]
Antaŭe tio funkciis, ĉu ĉe vi plu funkcias?

![image](https://user-images.githubusercontent.com/45429699/104937674-56c71000-59ae-11eb-9842-0b9398098fc8.png)

**Comment by shayani** [comment]
Jes, ĝi bone funkcias. Mi ĵus testis per Firefox kaj Safari.
