### ISSUE TITLE
Subpaĝo 'Registritaj prelegoj'

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#339]
Tre plaĉus al mi, se aldoniĝus al ES subpaĝo kiu donas superrigardon de disponeblaj registritaj prelegoj. Pro la pandemio ekzistas amaso da ili! 

Mi proponas prezenti la diversajn prelegojn ekzemple per bildo en Jutubo + ligilo al la Jutubo + al la evento en ES.

Ĉu realigebla? Mi volonte helpos pri enhava kompletigo.

![2EDBBD50-977F-4D8C-8FD3-EFD564E883E5](https://user-images.githubusercontent.com/45429699/105613104-b400fe00-5dc0-11eb-87e5-45fdf985ff49.jpeg)
![E3023456-2FA3-4D52-AD4C-A17E617052C7](https://user-images.githubusercontent.com/45429699/105613141-fe827a80-5dc0-11eb-8bc3-3d3a7f346606.jpeg)
![4E283E5E-0388-412C-B25F-1D750D411F1F](https://user-images.githubusercontent.com/45429699/105613142-05a98880-5dc1-11eb-9e5c-e5e63468b29a.jpeg)

**Comment by shayani** [comment]
Jes, tute farebla kaj bona ideo.

Ĉu vi havas ideon kiel volas aperigi ĝin en ES? Ĉu vi konas "similan" retejon por per kie mi povas inpiri min pri la fasado?

**Comment by yvesnevelsteen** [comment]
![2432D229-CA9F-4029-9059-594F25343AB9](https://user-images.githubusercontent.com/45429699/105646096-357a8e00-5e9e-11eb-846d-5c5422c3a1fa.jpeg)

**Comment by shayani** [comment]
Mi cerbumas pri tio. Mi planas ebligi event-adminstrantojn aldoni ligilojn de videoj en evento. Tiel, aŭtomate, ES aldonos tiujn videojn al paĝo "videoj.eventaservo.org" kaj samtempe la evento havos pli informoj kiel "histori-dokumento".

Ĉu vi konsentas aŭ havas pli bonan ideon?

**Comment by yvesnevelsteen** [comment]
Plaĉas al mi tiu ideo. Mi tre scivolas.

**Comment by JabieroKubo** [comment]
Bonege ke tio estas/os aldonata al la retejo!
Mi mem prelegis pri ES antaŭ longe en mia asocio (laŭ mia memoro ĝi estas en https://www.slideshare.net/radioamatoro/), eble oni distingu inter:

- informprelego (prelego pri ES, kio ĝi estas, kiel ĝi fartas, statistikoj ks.)
- gvidilo (kiel uzi ES kaj ties funkcioj)
- novaĵo (novaĵoj pri ES en retejoj kaj revuoj)
