### ISSUE TITLE
Aŭtomata alklakebligo de ligiloj en la tekstujo

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#340]
Eblas igi ligilon alklakebla, sed enigantoj ne faras tion.
Ĉu eblus tion iel aŭtomatigi?

![4A0FC519-5D10-490C-94D2-B633954DBFEE](https://user-images.githubusercontent.com/45429699/105629616-52827300-5e44-11eb-9d04-d4c897e017c4.jpeg)

**Comment by shayani** [comment]
TRIX Editor ne eblas aŭtomate krei ligilon (vidu https://github.com/basecamp/trix/issues/167).

Eble en ES v3 ni povos uzi alian ilon kron Trix.

**Comment by shayani** [comment]
Rimarku ke Github aŭtomate keas ligilon ;)
