### ISSUE TITLE
Redakti la landon de ES-uzanto + statistikoj

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#343]
Mi scias, ke ĉi tiu virino estas litova.
Estus laŭ mi bone, se administranto (kaj ankaŭ la uzanto mem) povas ŝanĝi tiun informon.

Ankaŭ estus bone, fari statistikon pri ES-registrintoj laŭ lando.

![6412893E-7C9D-41D6-ADEE-9F27F1187BCB](https://user-images.githubusercontent.com/45429699/105732553-dd409c00-5f30-11eb-8944-f2dd13ea63a0.jpeg)

**Comment by shayani** [comment]
La uzanto povas ŝanĝi tion per sia profil-redaktilo.

Pri la administranta ilo por fari tion, eblas. Nuntempe, mi povas fari tion mane.
