### ISSUE TITLE
Defaŭlta antaŭvido de ligilo en Telegram kaj Facebook: ni ekuzu la bildon de organizo, ne plu tiun de ES

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#345]
Laŭ mi, kiam iu konigas ligilon al ES-evento, estonte ni ne plu montru la emblemon de ES, sed de la organizo - se tia bildo estas alŝutita al la organiza paĝo.

Nun aspektas ĉi tiel evento de TEJO sen aldonita bildo:
![image](https://user-images.githubusercontent.com/45429699/106262174-e8dade00-6222-11eb-88ba-aa6cc24822c7.png)

Ĝi aspektu ĉi tiel:
![image](https://user-images.githubusercontent.com/45429699/106262984-12e0d000-6224-11eb-8840-b313476223f0.png)

(nu, eblas fajnigi)

Atenton: evidente, tio nur validas por eventoj sen al ĝi aldonita bildo.

**Comment by shayani** [comment]
Estas la sama solvo de #402
