### ISSUE TITLE
Serĉilo: ĝi montru ankaŭ uzantojn (nur por admin)

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#346]
Por "malbremsi min", mi proponas, ke vi montru ankaŭ uzantojn kiam oni serĉas per kapvorto.

Mi ekzemple volis rapide aliri la paĝon de Stela, sed devas ĉiufoje sekvi jenajn paŝojn:
1) iri al https://eventaservo.org/admin/users
2) serĉi je la nomo de uzanto
3) trovi la uzanton inter 900+ aliaj...

Serĉo por 'Stela' (https://eventaservo.org/serchilo?query=stela) donu ĉi tiun rezulton por administranto de ES:

![image](https://user-images.githubusercontent.com/45429699/106270476-5c361d00-622e-11eb-8636-301df7b9f3ca.png)

(8 rezultoj entute - mi nur aldonis 3 por ke estu klare, kion mi konkrete celas)

**Comment by shayani** [comment]
Jes, mi faros tion. Kial nur por administrantoj?
