### ISSUE TITLE
Diskonigilo: ne estas en ordo en poŝtelefono

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#35]
Ĉu eblas iom re-aranĝi la ekranon por ke ankaŭ sur poŝtelefono bone aspektu?
Cetere: estus bone tie aldoni ankaŭ butonon "kopii ligilon" kiu kopias la URL-on de la evento.

![f18b6d2f-3959-4768-bba0-9e55ea888f1d](https://user-images.githubusercontent.com/45429699/52902935-0bcb7d80-3218-11e9-9a41-929b5f01b188.jpeg)

**Comment by shayani** [comment]
![img_1669744ae4eb-1](https://user-images.githubusercontent.com/1488409/52938604-da9a9c80-3340-11e9-9ea8-076209c248db.jpeg)
Ĉu vi povas kontroli se ĝi okazas en alia evento? Eble tio okazas pro la longeco de la Facebook ligilo suba, kiu larĝigas la paĝon.

**Comment by shayani** [comment]
Ne estas problemo kun la diskonigilo, sed kun la longeco de retpaĝa ligilo:

![img_84527c95b87b-1](https://user-images.githubusercontent.com/1488409/52938787-51379a00-3341-11e9-8e36-73d35855006c.jpeg)

**Comment by shayani** [comment]
Sugesto: Tranĉi la ligilon al nur la domajna nomo. Ĝi aperos pli mallonga, tamen, kion oni alklakas ĝin, iros al la ĝusta retpaĝo.

**Comment by yvesnevelsteen** [comment]
Jes, ŝajnas esti bona solvo. Almenaŭ se klaras ke io sekvas post la domajna nomo, ekzemple ĉi tiel:
www.facebook.com/events/...

**Comment by shayani** [comment]
Propono: Krei butonon: "Vizitu la retpaĝon"
