### ISSUE TITLE
Alŝuti reklamon: malebligi la aperigon de nuligitaj eventoj

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#350]
Se evento estas nuligita, oni ne plu reklamas ĝin. Ne havas do sencon montri nuligitajn eventojn en la falmenuo, tie kie oni aldonas reklamon. Jam kelkfoje malhelpas tio al mi.

![6BF0263C-AD38-4FBE-B2C9-C590A63D55A9](https://user-images.githubusercontent.com/45429699/106370436-4887d500-635a-11eb-99c4-fe1185a5c610.jpeg)

**Comment by shayani** [comment]
Ne plu necesas pro #440
