### ISSUE TITLE
Limigi la longon de mallonga ligilo

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#352]
Yves Nicolas erare metis la adreson de Zoom-rendevuo en la kadron "Mallonga ligilo" (kiu entenas referencojn de Eventa Servo). Tiel ekestis teĥnika problemo. Do gravas limigi la longon de mallonga ligilo kaj afiŝi atentigan mesaĝon, se iu provas ion tian.

**Comment by yvesnevelsteen** [comment]
Nova evento kreita de Yves NICOLAS:

Blagoj kaj 񁒝ercaj anekdotoj
mardo,  9 februaro 2021
Caen (FR)

Ni inter񁒝an񁂝u humura񁂵ojn !

https://eventaservo.org/e/Yves%20NICOLAS%20vous%20invite%20%C3%A0%20une%20r%C3%A9union%20Zoom%20planifi%C3%A9e.%20%20Sujet%C2%A0:%20Zoom%20meeting%20invitation%20-%20R%C3%A9union%20Zoom%20de%20Yves%20NICOLAS%20Heure%C2%A0:%209%20f%C3%A9vr.%202021%2006:30%20PM%20Paris%20%20Participer%20%C3%A0%20la%20r%C3%A9union%20Zoom%20https:%2F%2Fus02web.zoom.us%2Fj%2F5065783487%3Fpwd=MFRlbXhXSHQxa0l6dS83OXBoZThkZz09%20%20ID%20de%20r%C3%A9union%C2%A0:%20506%20578%203487%20Code%20secret%C2%A0:%200S1yGL%20Une%20seule%20touche%20sur%20l%E2%80%99appareil%20mobile%20+13017158592,,5065783487%23,,,,*434524%23%20%C3%89tats-Unis%20d%E2%80%99Am%C3%A9rique%20(Washington%20DC)%20+13126266799,,5065783487%23,,,,*434524%23%20%C3%89tats-Unis%20d%E2%80%99Am%C3%A9rique%20(Chicago)%20%20Composez%20un%20num%C3%A9ro%20en%20fonction%20de%20votre%20emplacement%20%20%20%20%20%20%20%20%20+1%20301%20715%208592%20%C3%89tats-Unis%20d%E2%80%99Am%C3%A9rique%20(Washington%20DC)%20%20%20%20%20%20%20%20%20+1%20312%20626%206799%20%C3%89tats-Unis%20d%E2%80%99Am%C3%A9rique%20(Chicago)%20%20%20%20%20%20%20%20%20+1%20346%20248%207799%20%C3%89tats-Unis%20d%E2%80%99Am%C3%A9rique%20(Houston)%20%20%20%20%20%20%20%20%20+1%20646%20558%208656%20%C3%89tats-Unis%20d%E2%80%99Am%C3%A9rique%20(New%20York)%20%20%20%20%20%20%20%20%20+1%20669%20900%209128%20%C3%89tats-Unis%20d%E2%80%99Am%C3%A9rique%20(San%20Jose)%20%20%20%20%20%20%20%20%20+1%20253%20215%208782%20%C3%89tats-Unis%20d%E2%80%99Am%C3%A9rique%20(Tacoma)%20ID%20de%20r%C3%A9union%C2%A0:%20506%20578%203487%20Code%20secret%C2%A0:%20434524%20Trouvez%20votre%20num%C3%A9ro%20local%C2%A0:%20https:%2F%2Fus02web.zoom.us%2Fu%2Fkcb0QKoTRb

**Comment by shayani** [comment]
Forviŝita
