### ISSUE TITLE
retservo (webservice)

### ISSUE THREAD

**Issue by axel584** [eventaservo/eventaservo#363]
Estus bone havi retservo kion ni povus uzi por listigi eventojn kaj afiŝi ilin sur nia retpaĝo : http://esperanto-france.org/
(tiel, ni ne plu bezonus registri la informojn pri eventoj sur nia retpaĝo, ni rekte indikos ilin sur ES)

**Comment by shayani** [comment]
Saluton Axel. Precize kion vi celas?
Nuntempe mi programas API (REST/GraphQL) por ke aliaj programistoj povas listigi/redakti eventojn rekte de aliaj sistemoj/paĝoj. 
Ĉu tio estas kion vi celas?

**Comment by axel584** [comment]
Jes, ĝuste ! ❤

**Comment by shayani** [comment]
Hola @axel584. Mi pardonpetas pro la malfruo tamen mi ĵus havis kunsido pri tiu temo kaj nun ni programos API pli rapide. Baldaû estos novaĵo pri ĝi :)

**Comment by shayani** [comment]
Mi komencis krei ĝin. La dokumentao estas/estos cê https://eventaservo.org/docs/api/v2

**Comment by axel584** [comment]
Dankon @shayani . Kiel mi povas akiri "bearer token" ? Ĉu mi uzu mian propran konton ? Ĉu mi kreas specifan konton por tio ?
Dankon al vi.

**Comment by shayani** [comment]
Saluton @axel584. Mi programas tion kaj baldau ghi estos disponebla che la uzant-profil-pagho. (https://github.com/eventaservo/eventaservo/issues/413)
