### ISSUE TITLE
2 lingvaj informoj

### ISSUE THREAD

**Issue by axel584** [eventaservo/eventaservo#374]
Saluton,
Mi dezirus scii ĉu eblus aperigi informojn en 2 lingvoj (nacia kaj esperanto). Tiel, estus pli bone por konigi kursojn por komencantoj aŭ tiaj eventoj kiuj celas "ankoraŭ ne" esperantistojn ;) 
Dankon pro viaj opinioj pri tio.

**Comment by shayani** [comment]
Saluton Axel. Jes, ni intencas fari tion :) Tamen ne eblas informi (nun) kiam ĝi okazos.
