### ISSUE TITLE
Ĉu aldoni la eblon aldoni pliajn ligilojn al evento?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#42]
Ĉu aldoni pliajn ligilojn: al socia retejo, al aliĝilo, al diversaj artikoloj pri la evento ktp.

Mi rimarkas ke pri la evento BET (kien mi iros) ekzemple aperas multe da artikoloj en diversaj lokoj; estus bone ilin facile retrovi per ES. Tio donus kroman kialon viziti ES, ĉiam helpas...

Nun jam eblas aldoni diversajn ligilojn en la kampo 'Enhavo', sed eble estus pli "facila kaj invita" krei apartajn kromajn kampojn por tio.

**Comment by shayani** [comment]
Kiajn ligilojn vi sugestas?

Facebook-paĝo
Oficiala retpaĝo
Aliĝilo
Skype kontakto
Telegram kontakto, ktp?

**Comment by yvesnevelsteen** [comment]
Eble aldonindus sistemon kiel la aplikaĵo Contacts en iOS.

![5e7e8462-b94b-4c37-8e4b-bcdd94155da9](https://user-images.githubusercontent.com/45429699/53194372-82e78400-3613-11e9-9e42-2689df18b07b.png)

**Comment by yvesnevelsteen** [comment]
Jen kelkaj ideoj pri ligiloj:
- al aliĝilo
- al listo de aliĝintoj
- al diversaj artikoloj pri la evento (vidu ekzemple http://sezonoj.ru/bet55/)
- al artikolo pri la evento en Vikipedio
- al filmetoj pri la evento (reklamaj aŭ raportaj)
- al fotopaĝo(j) pri la evento
- al Facebook-paĝo de la evento
- al Telegram-grupo pri la evento

Por regule revenantaj eventoj, mi imagas ke baldaŭ ekestos 'Eventa paĝo' kiu donas superrigardon, simile al Meetup https://www.meetup.com/Esperanto-Toronto/

**Comment by yvesnevelsteen** [comment]
Mi imagas ion tian, responde al kritikoj. Io tia laŭ mi povas esti relative rapide realigebla; poste eblos plibonigi.

![utilaj ligiloj2](https://user-images.githubusercontent.com/45429699/53570592-2cc09680-3b67-11e9-86f2-7ca765c46b8e.jpg)

**Comment by shayani** [comment]
Mi fermas la Issue pro manko de aktiveco.
