### ISSUE TITLE
Ebleco filtri plurtagojn eventojn

### ISSUE THREAD

**Issue by bpeel** [eventaservo/eventaservo#43]
Mi pensas ke estus bona ideo fari distingon inter plurtagaj eventoj kaj lokaj unu-tagaj / unu-vesperaj eventoj. Ekzemple se mi volas plani miajn feriojn mi povus rigardi la liston de eventoj en la tuto de eŭropo, sed ne helpas vidi tre malgrandajn eventojn kiuj daŭras nur unu vesperon. Estus bone se mi povus vidi la liston de eventoj kiuj daŭras plurajn tagojn ĉar estas pli probable ke mi povus longe vojaĝi por ĉeesti ilin.

**Comment by shayani** [comment]
Certe estas interesa ideo krei filtrilojn 👍 Laŭ eventa longeco, ktp
