### ISSUE TITLE
Aldoni malgarantian tekston al la retejo

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#44]
Eble surbaze de https://eo.wikipedia.org/wiki/Vikipedio:Malgarantio?wprov=sfti1

**Comment by shayani** [comment]
Jen ligilo por kunskribi tiun tekston: https://docs.google.com/document/d/1d1P899TAlHb8ArPLNGsyVyo4n2ZRsLNFGq7F8AUPDe4/edit?usp=sharing 

Kiuj sin taksas kapabla helpi skribi tiajn informojn, bv helpi.

**Comment by shayani** [comment]
Mi fermas la Issue pro manko de aktiveco.
