### ISSUE TITLE
Plibonigo de la aspekto: Tim Owen proponas helpi

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#48]
Tim Owen: "mi memoras esti leginta, ke fernando estus danka ricevi helpon de iu sciante CSS por plibonigi la aspekton. kaj hazarde beligado estas mia relativa forto. mi esperas iel trovi iom da libertempo por proponi iom da helpo."

**Comment by Meddysong** [comment]
Mi daŭre proponas kaj faros pli oficiale baldaŭ! Mi havas propran projekton por UEA, kiun mi esperas baldaŭ fini kaj poste estos libera por plia.

Intertempe, mi ludos per la API por uea.facila.org kaj kompreneble devos verki stilon por ĝi.
