### ISSUE TITLE
Eble ŝanĝu 'Urbo' al 'Loko', ne ĉiuj lokoj estas urboj

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#52]

**Comment by shayani** [comment]
Ne ĉiuj lokoj estas urboj. Se oni plenumas tiun kampon per alia nomo kiu ne estas urbonomo, G ne trovos la ĝustan koordinatojn.

**Comment by RobinvanderVliet** [comment]
![image](https://user-images.githubusercontent.com/692029/53683080-06ccfa80-3cfd-11e9-8eba-9ce1e4cf94f4.png)
@shayani Escharen estas vilaĝo kaj ne urbo. Google Maps trovas ĝin.
