### ISSUE TITLE
Grupigi eventojn laŭ regionoj

### ISSUE THREAD

**Issue by shayani** [eventaservo/eventaservo#53]
Sugesto de Raimund Riedel: Grupigi eventoj laŭ regionoj, ne laŭ politikaj limoj. Tiel, homoj kiu vivas en regiono kiu komprenas el multaj landoj kapablos vidi la eventojn proksimaj.

**Comment by shayani** [comment]
Alia ideo por solvi tian situacion: Listigi eventojn laŭ proksimeco.

**Comment by yvesnevelsteen** [comment]
Estus tre praktike kaj impone (kaj pli esperantistece) aŭtomate listigi en la ĉefpaĝo de ES ĉiujn eventojn laŭ dato kaj laŭ proksimeco, ekzemple 200-300 km ĉirkaŭ la loko kie la uzanto uzas retumilon. Poste uzante havu la eblon agordi laŭplaĉe. Estus bonege, ĉar tiel homoj ne plu ĉiufoje devus trairi plurajn menuerojn por trovi eventojn ĉirkaŭ si. Limigi la nombron de alklakoj helpos por pli popularigi ES (homoj estas pigraj). Precipe gravus tiu nova eblo por etaj landoj kiel Belgio kaj Nederlando, sed laŭ mi jen la nova prioritato.
