### ISSUE TITLE
Mi ne sukcesas aldoni finan horon

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#55]
Provu ĉe la evento 
https://eventaservo.org/eventoj/VuXPi23NN2Y_VsMU aldoni:
- 17:00 komenco
- 16:00 fino

Mi ne sukcesas.

**Comment by shayani** [comment]
Mi sukcesis. Estas problemo kun GeoNames por trovi la ĝustan horzonon. Mi jam havas planon por trovi la horzonon alimaniere se Geonames ne funkcias.
