### ISSUE TITLE
Malaboni landajn kalendarojn: ĉu ie ĉe la profilo de uzanto?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#57]
Nun homoj kiuj abonas la kalendaran de iu lando, ricevas pri tio retmesaĝon. Eblas malaboni ĝin nur alklakante la ligilon en la retmesaĝo. Se poste homoj perdas tiun mesaĝon, ili ne plu povos malaboni. Tial estus pli bone ebligi malaboni aliloke, ekzemple ĉe la profilo (tie kie nun peras Retlistoj - Semajna resumo)

**Comment by shayani** [comment]
Mi rekreos al abonon kaj maladonon de tiu informilo
