### ISSUE TITLE
Horzonoj: traduki la nomojn

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#58]
Roĉjo volontulas. Post kiam la dosiero estos tradukita, Yves disponigos ĝin ankaŭ pere de Komputeko.

**Comment by yvesnevelsteen** [comment]
Fernando: Ne estas tiel simple, ĉar nuntempe mi uzas la aŭtomata listo de horzonoj. Por traduki, mi unue bezonas krei datumbazan "table"-n kaj aldoni la tradukojn. 

Sed eble eblas tion fari por v2.0

**Comment by shayani** [comment]
@yvesnevelsteen, mi trovis simplan metodon por traduki la tempozonon: redakti tiun ĉi doesieron: https://github.com/eventaservo/eventaservo/blob/v2.0/config/locales/epo.yml
