### ISSUE TITLE
Malrapidiĝo subita (ĉu pro la flago de Domingo?)

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#61]
Post aldonado de du eventoj en Domingo (https://eventaservo.org/Ameriko/Domingo), ES subite malrapidiĝis. Temas nur pri la parto Ameriko; mi supozas ke estas problemo pri la flago de Domingo.

**Comment by shayani** [comment]
La flago de Domingo samas al ĉiuj aliaj flagoj. En mia komputilo kaj iPhone tio ne okazas.

**Comment by yvesnevelsteen** [comment]
Mi poste faros kelkajn eksperimentojn, ekzemple forigos la eventojn en Domingo kaj vidos ĉu la tuto plirapidiĝos. Ni vidos.
