### ISSUE TITLE
Elekti lokon en mapo: ĉu ebligi korekteblon se Google Geocode eraras?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#63]
Paul: En mia eksa eventoprojekto mi devigis la uzanton mem elekti la lokon en mapo... Mi supozas ke Google ne tro precizas kun esperantaj nomoj... Ni povus antaŭmontri adreson en la formularo post la eventosendo de la uzanto ke li povus korekti mem mane en ES eble, ĉu? http://p4w5.eu/eo-renkontoj/build/aldoniEventon.html

Fernando: Jes, estas bona ideo, tamen mi ne sufiĉe spertas pri Javascript por fari tion nuntempe.

Paul: Ok, mi komprenas, sed vi povas tiokaze nur lasi la aŭtomatdivenita loko sen korekto... **Nur estus korekteblo kiam vi scias ke la diveno estas malpreciza**, aŭ tiel mi imagas ĝin.

**Comment by paulwuertz** [comment]
Jen propono (nur estas la formularo, do ne funkcianta retpaĝo ;))
http://p4w5.eu/es/koord-select/
