### ISSUE TITLE
Vidu la eventon rekte -> Vidi la eventon en la retejo

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#64]
Mi rekomendas ŝanĝi la tekston de tiu butono

![f5a30a7b-ffdd-4ce2-8346-111b8a8b8b14](https://user-images.githubusercontent.com/45429699/53583211-6b634a80-3b81-11e9-803f-3608aa1a62ca.png)

**Comment by shayani** [comment]
Al kio?

**Comment by yvesnevelsteen** [comment]
Al " Vidi la eventon en la retejo"

**Comment by shayani** [comment]
Malpli da vortoj pli bonas ;)

"Legu pli"

**Comment by yvesnevelsteen** [comment]
"Legi pli"
