### ISSUE TITLE
URL de evento: ĉu ebligi pli facilan tajpadon?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#65]
Malfacilas publikigi en papera revuo ligilon kiel https://eventaservo.org/eventoj/qKdZiWkK8hRX4av7 - homoj ne entajpos tion. 

Fernando esploros solvon per facile tajpebla kodo kiel www.evenservo.org/145214

**Comment by JabieroKubo** [comment]
ĉu ne eblus eĉ pli facila kiel
[www.evenservo.org/UniversalaKongreso2019](url)

**Comment by shayani** [comment]
> ĉu ne eblus eĉ pli facila kiel
> [www.evenservo.org/UniversalaKongreso2019](url)

Ne. Imagu lokaj aranĝoj: Maja Esperata Renkontiĝo de Ĵoan-Pesso

https://eventaservo.org/MajaEsperataRenkontiĝodeĴoan-Pesso

Kiu estus la ligilo en la venonta jaro? Aŭ se iu evento okazas 4 foje monate?

Mi konsentas ke eblas plibeligi la kodon, tamen ĝi povas esti la eventa nomo.

**Comment by yvesnevelsteen** [comment]
Mi favoras facile tajpeblan ligilon kiel www.eventaservo.org/2019/07/UK2019 laŭ la principo de WordPress. Por eventoj utilus tuj per la ligilo ekscii en kiu monato ĝi okazos.

**Comment by shayani** [comment]
La ligilo *devas* esti neŝanĝebla. Neniam. Se tiu evento ial ŝanĝas la daton al Aŭgusto, la ligilo ŝanĝos.

Ni plu cerbumos...

**Comment by yvesnevelsteen** [comment]
Vi pravas. Pri tio mi ne pensis.

**Comment by yvesnevelsteen** [comment]
Eble eblus per https://yourls.org/

YOURLS stands for Your Own URL Shortener. It is a small set of PHP scripts that will allow you to run your own URL shortening service (a la TinyURL or Bitly).

Running your own URL shortener is fun, geeky and useful: you own your data and don't depend on third-party services. It's also a great way to add branding to your short URLs, instead of using the same public URL shortener everyone uses.

**Comment by yvesnevelsteen** [comment]
Eble sistemo kiel tiu de la retbutiko de FEL taŭgus. 

Oni programis https://retbutiko.be/trovu/[serĉi laŭ slosilvorto]

Vidu ekzemple https://retbutiko.be/trovu/komputeko
