### ISSUE TITLE
Kunigi la diversajn nomojn por la sama urbo

### ISSUE THREAD

**Issue by bpeel** [eventaservo/eventaservo#67]
Mi rimarkas ke kiam oni kreas eventon foje oni uzas la nomon de la urbo en Esperanto kaj foje en loka lingvo. Rezulte oni havas du malsamajn ligilojn kaj listojn por eventoj en la sama urbo.

Eble la retejo povus havi datumbazon de alternativaj nomoj por urboj tiel ke ekzemple kiam oni kreas eventon en «Francio / Lyon» ĝi scios ke la evento devus aperi en la sama listo kun eventoj en «Francio / Liono».

**Comment by yvesnevelsteen** [comment]
Mi ankaŭ rimarkis tion kaj ĝis nun ĉiufoje mane korektis.
