### ISSUE TITLE
API por aliri liston de eventoj

### ISSUE THREAD

**Issue by RobinvanderVliet** [eventaservo/eventaservo#7]
Lastatempe mi iom cerbumas pri publike alirebla API. Laŭ mi persone, ĉefe utilas havi API por aliri liston de ĉiuj eventoj.

La jenaj datumoj estas utilaj por programistoj:
* identiga parto de la ligilo _(ekzemple_ `eP4qn7QlCYuyLysl`)
* titolo de la evento _(ekzemple_ `104-a Universala Kongreso`)
* priskribo de la evento _(ekzemple_ `Vivanta Naturo, Floranta Kulturo`)
* retpaĝo de la evento _(ekzemple_ `https://uea.org/alighoj/uk_alighilo`)
* nomo de la urbo _(ekzemple_ `Lahti`)
* dulitera kodo de la lando _(ekzemple_ `fi`)
* komenca dato _(ekzemple_ `2019-07-20`)
* fina dato _(ekzemple_ `2019-07-27`)

Estus bone, se la API povus redoni datumojn en pluraj malsamaj dosiertipoj (JSON, JSONP kaj XML).

Jen kelkaj ekzemploj de mi:

Rezulto por https://eventaservo.org/api/events/?format=json (`Content-Type: application/json`)
```json
[{"id":"eP4qn7QlCYuyLysl","title":"104-a Universala Kongreso","description":"Vivanta Naturo, Floranta Kulturo","website":"https://uea.org/alighoj/uk_alighilo","city":"Lahti","country":"fi","start":"2019-07-20","end":"2019-07-27"},{"id":"ctbkvMu3gft5kVUp","title":"75-a Internacia Junulara Kongreso, IJK","description":"ĈEFTEMO DE LA KONGRESO: KONTRAŬ ANTAŬJUĜOJ","website":"https://ijk2019.tejo.org/","city":"Liptovský Hrádok","country":"sk","start":"2019-07-28","end":"2019-08-04"},{"id":"ZMQHEVXK4KuELUlK","title":"11-a Junulara E-Semajno, JES","description":"Festu la novan jaron en bonega etoso kun pli ol 200 homoj el ĉirkaŭ 20 landoj!","website":"http://jes.pej.pl/eo/","city":"Głuchołazy","country":"pl","start":"2019-12-27","end":"2020-01-03"}]
```

Rezulto por https://eventaservo.org/api/events/?format=json&callback=traktiEventojn (`Content-Type: application/javascript`)
Estas pli-malpli la sama afero, krom ke estas "traktiEventojn(...);" ĉirkaŭ la datumoj. La nomo de tiu funkcio estu agordebla per la parametro "callback".
```javascript
traktiEventojn([{"id":"eP4qn7QlCYuyLysl","title":"104-a Universala Kongreso","description":"Vivanta Naturo, Floranta Kulturo","website":"https://uea.org/alighoj/uk_alighilo","city":"Lahti","country":"fi","start":"2019-07-20","end":"2019-07-27"},{"id":"ctbkvMu3gft5kVUp","title":"75-a Internacia Junulara Kongreso, IJK","description":"ĈEFTEMO DE LA KONGRESO: KONTRAŬ ANTAŬJUĜOJ","website":"https://ijk2019.tejo.org/","city":"Liptovský Hrádok","country":"sk","start":"2019-07-28","end":"2019-08-04"},{"id":"ZMQHEVXK4KuELUlK","title":"11-a Junulara E-Semajno, JES","description":"Festu la novan jaron en bonega etoso kun pli ol 200 homoj el ĉirkaŭ 20 landoj!","website":"http://jes.pej.pl/eo/","city":"Głuchołazy","country":"pl","start":"2019-12-27","end":"2020-01-03"}]);
```

Rezulto por https://eventaservo.org/api/events/?format=xml (`Content-Type: application/xml`)
```xml
<?xml version="1.0" encoding="UTF-8"?><events><event><id>eP4qn7QlCYuyLysl</id><title>104-a Universala Kongreso</title><description>Vivanta Naturo, Floranta Kulturo</description><website>https://uea.org/alighoj/uk_alighilo</website><city>Lahti</city><country>fi</country><start>2019-07-20</start><end>2019-07-27</end></event><event><id>ctbkvMu3gft5kVUp</id><title>75-a Internacia Junulara Kongreso, IJK</title><description>ĈEFTEMO DE LA KONGRESO: KONTRAŬ ANTAŬJUĜOJ</description><website>https://ijk2019.tejo.org/</website><city>Liptovský Hrádok</city><country>sk</country><start>2019-07-28</start><end>2019-08-04</end></event><event><id>ZMQHEVXK4KuELUlK</id><title>11-a Junulara E-Semajno, JES</title><description>Festu la novan jaron en bonega etoso kun pli ol 200 homoj el ĉirkaŭ 20 landoj!</description><website>http://jes.pej.pl/eo/</website><city>Głuchołazy</city><country>pl</country><start>2019-12-27</start><end>2020-01-03</end></event></events>
```

Rezulto por https://eventaservo.org/api/events/?format=ics (`Content-Type: text/calendar`)
"DTSTAMP" enhavu la daton, kiam oni lastfoje ŝanĝis la eventon.
```vcalendar
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Eventa Servo//Eventa Servo//EO
CALSCALE:GREGORIAN
BEGIN:VEVENT
UID:eP4qn7QlCYuyLysl
DTSTAMP:20190101T000000Z
DTSTART:20190720T000000Z
DTEND:20190727T000000Z
SUMMARY:104-a Universala Kongreso
LOCATION:Lahti, FI
DESCRIPTION:Vivanta Naturo, Floranta Kulturo
END:VEVENT
BEGIN:VEVENT
UID:ctbkvMu3gft5kVUp
DTSTAMP:20190101T000000Z
DTSTART:20190728T000000Z
DTEND:20190804T000000Z
SUMMARY:75-a Internacia Junulara Kongreso, IJK
LOCATION:Liptovský Hrádok, SK
DESCRIPTION:ĈEFTEMO DE LA KONGRESO: KONTRAŬ ANTAŬJUĜOJ
END:VEVENT
BEGIN:VEVENT
UID:ZMQHEVXK4KuELUlK
DTSTAMP:20190101T000000Z
DTSTART:20191227T000000Z
DTEND:20200103T000000Z
SUMMARY:11-a Junulara E-Semajno, JES
LOCATION:Głuchołazy, PL
DESCRIPTION:Festu la novan jaron en bonega etoso kun pli ol 200 homoj el ĉirkaŭ 20 landoj!
END:VEVENT
END:VCALENDAR
```

**Comment by shayani** [comment]
Kial la neceso de 'traktiEventojn' metodo?

**Comment by RobinvanderVliet** [comment]
Oni nomas tion [JSONP](https://en.wikipedia.org/wiki/JSONP) kaj ĝi povas esti utila por JavaScript-programistoj de aliaj retejoj.

Ekzemple oni povus fari retejon kun la JavaScript-funkcio `riceviEksterajnEventojn(eventoj)`. Kaj poste oni nur bezonas aldoni `<script src="https://eventaservo.org/api/events/?format=jsonp&callback=riceviEksterajnEventojn">`.

**Comment by Meddysong** [comment]
Saluton!

Mi interesiĝas pri API, ĉar tute ne estus sencohave devi permane aldoni eventojn de alia retejo, kiel ni devas fari nun. Kontraŭ uzo de API, mi invitus homojn aldoni siajn kunvenojn ĉe via retejo kaj nuligos nian propran kalendaron, ĉar tiam ni povus simple montri ĉiujn aranĝojn, kiuj aperas ĉe via retejo.

**Comment by shayani** [comment]
Preta je 
https://github.com/eventaservo/eventaservo/commit/7a37be0240578a797a474d83258e9757e4dbd5a9
