### ISSUE TITLE
Dissendado de retmesaĝo post kreado de nova evento: ĉu iom atendi?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#74]
Mi rimarkis ke en praktiko, ofte tuj post kiam mi aldonis novan eventon, mi ŝanĝas ĝin. Povas esti ke mi eraris aŭ kompletigos ĝin per bildo ktp. Tial eble dissendi mesaĝon pri nova evento eble indus fari duonhoron post kiam ĝi estas kreita.

**Comment by shayani** [comment]
Tio jam okazas. La estraro ricevas post 5 minutoj kaj la uzanto post 1 horo.
