### ISSUE TITLE
Krei novan eventon kaj poste ŝanĝi ĝian "respondeculon"

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#77]
Mi pripensis ke povus esti bona ideo ke ni administrantoj kreu "bazan eventon" kaj poste indiku "respondeculon". Malfacilas (mi foje miras) konvinki kelkajn homojn ek-kunlabori al Eventa Servo; povus esti Instigo demandi ke oni "kompletigu eventon" anstataŭ krei ĝin. Aktivuloj kutime estas bonintencaj kaj esprimas sian helpemon, sed ial tamen eĉ post plurfoja insistado ne kreas sian unuan eventon.

Ankaŭ helpus doni "pli bonan impreson", ĉar nun iom tro ofte aperas mia nomo ĉe eventoj. Gravas por la "akceptiĝo far skeptikuloj" ke multaj malsamaj homoj aldonadas eventojn.

**Comment by shayani** [comment]
Mi konsentas. Gravas ke la respondeciulo jam ekzistas kiel uzanto de ES.

**Comment by yvesnevelsteen** [comment]
Jes ja. Tion mi celas: administranto (vi aŭ mi) kreas eventon kaj poste ni indiku respondecan uzanton.
Eble tiu ĉi persono povos esti aŭtomate avertita per retmesaĝo en kiu aperas invito kompletigi/administri la eventon: "Yves Nevelsteen, administranto de Eventa Servo, kreis por vi ĉi tiun eventon kaj indikis ke vi rajtas ŝanĝi, kompletigi aŭ forigi ĝin. Se vi havas demandon, ne hezitu kontakti lin pri tio." - io tia.

Necesos ĉe la evento aperigi alian nomon ol "Kreinto" aŭ ŝanĝi ĝin al "Respondeculo" kiam la persono kiu respondecas pri la evento ne estas ĝia kreinto.

**Comment by shayani** [comment]
Ne necesas krei novan kampon en la datumbazo. La kreinto (baldaŭ ĝi estos 'respondeciulo') kapablos "doni" la eventon al alia homo, kiu kapablos ŝanĝi da informojn.
