### ISSUE TITLE
API: Ne ordigas laŭ komenca_dato

### ISSUE THREAD

**Issue by Meddysong** [eventaservo/eventaservo#79]
Logike retejo, kiu montras eventojn okazontajn dum iu periodo, ordigos ilin laŭ dato, la plej proksimajn unualoke. La API tamen ne ordigas la rezultojn tiel.

Kontrolu ekzemple tiun ĉi ligilon: https://eventaservo.org/api/v1/events.json?user_email=VIA_NOMO&user_token=VIA_KODO&komenca_dato=2019-01-01&fina_dato=2019-01-02

La kvin eventoj havas la sekvajn komenca_tago:

- 2018-12-27
- 2018-12-27
- 2018-12-31
- 2018-12-28
- 2018-12-28

Tiel okazis ankaŭ en kontrolo, kiun mi faris hodiaŭ uzante la hodiaŭan daton kiel komenca_tago.

**Comment by shayani** [comment]
Mi korektos ĝin 👍
