### ISSUE TITLE
Ĉu krei "legilon" por Facebook- kaj Meetup-eventoj?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#80]
Mi pripensis ke povus esti bona ideo krei (unuavice por ES-administrantoj) "legilon" por Facebook- kaj Meetup-eventoj. Mi nun regule kopias datumojn de tiuj eventoj; permane fari tion daŭras iom, ĉar necesas kopii-alglui plurajn datumojn (Titolo, datoj, horoj, adreso ktp). Se eblus "alklakante unu butonon" transpreni plurajn bazajn datumojn surbaze de ligilo kiel ĉi tiu, eblus gajni tempon. Eble tio relative facilas, ĉar temas pri strukturitaj datumoj? (Sed mi ne povas taksi tion; mankas al mi spertoj pri programado)

https://www.facebook.com/events/2197861046968767/?ti=ia

**Comment by JabieroKubo** [comment]
Mi tute subtenas la ideon kaj eblecon aldoni facebook eventoj al la retejo ES.org laŭ ebleco kreita de fb pere de API oni kopias kodon iframe al kiu nur ŝanĝas la ligilon... mi iom montrs ĉe:
[https://qsl.net/co2mm/eventoj2.html]
kiel fari ja pri tio mi ne sukcesas helpi :(

**Comment by yvesnevelsteen** [comment]
Eble "legilo" por eventoj de EAB ankaŭ bonus, ĉar ankaŭ ili uzas strukturitajn datumojn. Vidu https://esperanto.org.uk/calendar/
