### ISSUE TITLE
Konto Yves2: kreado de evento sen aldono de horoj donas problemon

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#89]
Mi kreas ĝin je 5/5 kaj ĝi ne aperas. Ĉe 'Miaj eventoj' estas indikita 4/5.

**Comment by shayani** [comment]
Tio ne plu okazas, ĉu ne?

**Comment by yvesnevelsteen** [comment]
Daŭre okazas, sed normalas. Kiam oni kreas novan eventon hodiaŭ, ĝi komenciĝas je 00:00 - do antaŭ la horo de enigo. Ne gravas, ĉar neniu enigos eventon kiu okazas hodiaŭ. Kutime oni tion faras minimume semajnon antaŭe. Do eblas fermi ĉi tiun issue.
