### ISSUE TITLE
Turkio estas parte eŭropa kaj parte azia lando

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#92]
Ĉu vi povas krei du Turkiojn, samkiel vi faris por Rusio?

**Comment by shayani** [comment]
Ĉu tio vere necesas? Turkio ne estas tiom granda kiel Rusio, do la sama problemo ne okazos.

**Comment by yvesnevelsteen** [comment]
Laŭ mi jes. Turkio estas lando kiu ĉefe troviĝas en Azio, sur la duoninsulo Malgrand-Azio inter la Mediteraneo kaj la Nigra Maro. Malgranda parto de la plej granda urbo Istanbulo troviĝas en Eŭropo.

La situacio do tre similas kun Rusio (kun ĉefaj urboj en eŭropa parto, sed ĉefa landamaso en Azio).

**Comment by shayani** [comment]
Farita.
