### ISSUE TITLE
Kvankam Kartvelio estas azia lando, ĝi aperas ĉe Eŭropo en la mapo

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#94]
![ES-Kartvelio](https://user-images.githubusercontent.com/45429699/57614913-b682dc00-757a-11e9-8571-70e140e96bca.JPG)

**Comment by shayani** [comment]
Laŭ Vikipedio (https://eo.wikipedia.org/wiki/Kartvelio):

> Kartvelio aŭ Kartvelujo (kartvele საქართველო / Sakartvelo) estas lando en centra kaj okcidenta partoj de Kaŭkazio en la ekstrema **sud-oriento de Eŭropo**, ĉe la geografia limo inter Eŭropo kaj Azio...
