### ISSUE TITLE
Necesas ĉiam denove ensaluti sur iPad - mi plu esploris

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#96]
Evidentiĝas ke sur Safari de iPad mi tamen restas ensalutinta, nur necesas ĉiufoje denove ensaluti kiam oni sekvas ligilon de Facebook aŭ retpoŝta programo. Ĉu ekzistas por tio teknika solvo?

**Comment by shayani** [comment]
Kiam oni sekvas ligilon de Facebook aŭ de alia aplikaĵo kiu ne vere malfermas Safari/Chrome, tamen, kreas novan "virtualan retumilon", tiu nova retumilo estas "freŝa" (Cookie clean). Tial oni devas reensaluti. 

Laŭ mi ne estas teknika solvo por tio. Ŝajnas normala iPad konduko.

**Comment by yvesnevelsteen** [comment]
Bone, "solvita".
