### ISSUE TITLE
Ĉu ne troa emfazo je ES anstataŭ je la evento kiam oni ĝin konigas?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#97]
Se mi ne eraras, antaŭe estis afiŝita la alŝutita bildo ĉe konigita evento en Facebook. Nun aperas ĉiufoje grande EVENTA SERVO - tio estas iomete troigo. Ĉu eblus ŝanĝi tion?

Gravas emfazi la eventon (per bela bildo pri ĝi) kaj ne ES dum konigado.

![emfazo](https://user-images.githubusercontent.com/45429699/57696787-f10b7800-7651-11e9-88ad-e1957b1bf3dd.JPG)

**Comment by shayani** [comment]
Nuntempe ES montras la bildoj kiu estas alŝutita (per alŝutilo). Kiam la bildo estas en la enhavo, ne funkcias.

Eblas funkiigi tion, tamen mi bezonas atendi Rails 6.0 por ŝanĝi la enhavo por ActionText.

**Comment by yvesnevelsteen** [comment]
Askpektu ĉi tiel :-)
![emfazo2](https://user-images.githubusercontent.com/45429699/57704889-1785df00-7663-11e9-9d05-453c59addb37.JPG)
