### ISSUE TITLE
Horzono: kial aperas foje Etc/UTC kaj foje ne por sama loko?

### ISSUE THREAD

**Issue by yvesnevelsteen** [eventaservo/eventaservo#99]
Malklaras kial aperas ĉe la evento https://eventaservo.org/eventoj/_G_zGkU1uYEcQ2uE la horzono Etc/UTC dum ĉe https://eventaservo.org/eventoj/OcBzJUOgJTgifNJK aperas Ameriko/Novjorko. Ambaŭ eventoj okazas en la sama adreso.

**Comment by shayani** [comment]
Mi ne scias la kialon, sed estas riparita nun. Ni atendas se tio okazos denove al alia evento.
